### ISSUE TITLE
Tamagui Webpack Loader Error

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#1020]
### Current Behavior

In the latest version, I see an error: Tamagui Webpack Loader Error:
I am using tamagui-loader

Tamagui Webpack Loader Error:
   "undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at transformConfig (/node_modules/@tamagui/static/dist/cjs/extractor/generateTamaguiStudioConfig.js:66:21)
    at generateTamaguiStudioConfig (/node_modules/@tamagui/static/dist/cjs/extractor/generateTamaguiStudioConfig.js:46:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadTamagui (/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:60:3)
    at async Object.load [as loadTamagui] (/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:89:42)
    at async extractToClassNames (/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/node_modules/tamagui-loader/dist/cjs/loader.js:69:23)

### Expected Behavior

Compile without errors

### Tamagui Version

```markdown
1.15.34
```

### Reproduction

```markdown
tamagui.config.ts

import { config } from '@my/library';

export type Conf = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;


webpack.config
```tsx

              loader: 'tamagui-loader',
              options: {
  config: './tamagui.config.ts',
  components: ['@my/library', 'tamagui'],
  disableExtraction: isDevelopment,
},
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.78 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 111.0
    Safari: 16.4
```

**Comment by seeden** [comment]
@natew  I am not able to build project anymore with this issue

**Comment by seeden** [comment]
Version 1.5.33 is working fine. I moved to an older version

**Comment by natew** [comment]
Fix going out now, sorry for this. See `1.5.35`.

**Comment by natew** [comment]
* `1.5.36`

**Comment by natew** [comment]
@seeden I added a bit of safety there in .40 but you shouldn't be seeing this. Can you run with `DEBUG=tamagui` and show me the output?
