### ISSUE TITLE
Tamagui Webpack Loader Error

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#1029]
### Current Behavior

```sh
Tamagui Webpack Loader Error:
   Cannot read properties of undefined (reading 'tamaguiConfig')
TypeError: Cannot read properties of undefined (reading 'tamaguiConfig')
    at loadTamagui /node_modules/@tamagui/static/src/extractor/loadTamagui.ts:39:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.load [as loadTamagui] (/node_modules/@tamagui/static/src/extractor/createExtractor.ts:112:29)
    at extractToClassNames (/node_modules/@tamagui/static/src/extractor/extractToClassNames.ts:70:3)
    at Object.loader2 (/node_modules/tamagui-loader/src/loader.ts:60:23)
```

### Expected Behavior

Compile without errors

### Tamagui Version

```markdown
1.15.38
```

### Reproduction

```markdown
tamagui.config.ts

import { config } from '@my/library';

export type Conf = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;


webpack.config
tsx

              loader: 'tamagui-loader',
              options: {
  config: './tamagui.config.ts',
  components: ['@my/library', 'tamagui'],
  disableExtraction: isDevelopment,
},
```
```


### System Info

_No response_

**Comment by natew** [comment]
Latest release I added some safety but please run DEBUG=tamagui and send me logs

**Comment by seeden** [comment]
In 1.15.40 I see

```tsx
Tamagui Webpack Loader Error:
   Cannot destructure property 'components' of 'undefined' as it is undefined.
TypeError: Cannot destructure property 'components' of 'undefined' as it is undefined.
    at parseWithConfig (/node_modules/@tamagui/static/src/extractor/createExtractor.ts:136:7)
    at Object.parse (/node_modules/@tamagui/static/src/extractor/createExtractor.ts:131:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at extractToClassNames (/node_modules/@tamagui/static/src/extractor/extractToClassNames.ts:94:15)
    at Object.loader2 (/node_modules/tamagui-loader/src/loader.ts:60:23)
```

**Comment by clayrisser** [comment]
Getting the same error

**Comment by seeden** [comment]
fixed in latest release

**Comment by brianephraim** [comment]
I really want to integrate this library in my project.  I've tried everything but I keep getting this error.

```
error -asdfi/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/use-keyboard-visible/dist/cjs/useKeyboardVisible.js:25:27)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/use-keyboard-visible/dist/cjs/index.js:24:33)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/sheet/dist/cjs/Sheet.js:40:35)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/sheet/dist/cjs/index.js:25:25)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/dialog/dist/cjs/Dialog.js:57:20)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (asdf/node_modules/@tamagui/dialog/dist/cjs/index.js:18:25)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18) {
  page: '/'
}
```

package.json
```
{
  "name": "asdf",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "postinstall": "npm run sylink-git-hooks",
    "prebuild": "echo 'prebuild'",
    "build": "next build",
    "dev": "next dev",
    "export": "next export",
    "lint": "next lint",
    "lintfix": "next lint --fix",
    "tslint": "tsc",
    "start": "next start",
    "prettier": "./node_modules/.bin/prettier --write ./src",
    "prettier-check": "./node_modules/.bin/prettier --check ./src",
    "sylink-git-hooks": "ln -s ../../git-hooks/pre-commit .git/hooks/pre-commit && ln -s ../../git-hooks/pre-push .git/hooks/pre-push"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^4.3.8",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@expo/next-adapter": "^5.0.2",
    "@fortawesome/fontawesome-svg-core": "^6.3.0",
    "@fortawesome/free-regular-svg-icons": "^6.3.0",
    "@fortawesome/free-solid-svg-icons": "^6.3.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.16",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.12.2",
    "@next/font": "13.1.6",
    "@tailwindcss/forms": "^0.5.3",
    "@tanstack/react-table": "^8.7.9",
    "@types/node": "18.13.0",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "@types/styled-components-react-native": "^5.2.1",
    "@visx/axis": "^3.1.0",
    "@visx/curve": "^3.0.0",
    "@visx/gradient": "^3.0.0",
    "@visx/grid": "^3.0.1",
    "@visx/group": "^3.0.0",
    "@visx/legend": "^3.0.0",
    "@visx/marker": "^3.0.0",
    "@visx/mock-data": "^3.0.0",
    "@visx/pattern": "^3.0.0",
    "@visx/scale": "^3.0.0",
    "@visx/shape": "^3.0.0",
    "@visx/text": "^3.0.0",
    "@visx/xychart": "^3.0.1",
    "aws-amplify": "^5.0.16",
    "clsx": "^1.2.1",
    "dotenv": "^16.0.3",
    "eslint": "8.33.0",
    "eslint-config-next": "13.1.6",
    "lodash.has": "^4.5.2",
    "lodash.set": "^4.3.2",
    "nativewind": "^2.0.11",
    "next": "13.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "^0.71.7",
    "react-native-web": "^0.19.4",
    "react-redux": "^8.0.5",
    "react-spring": "^9.7.1",
    "redux": "^4.2.1",
    "redux-thunk": "^2.4.2",
    "styled-components": "^5.3.10",
    "tailwind-merge": "^1.10.0",
    "tamagui": "^1.26.0",
    "typescript": "4.9.5",
    "webpack": "^5.80.0"
  },
  "devDependencies": {
    "@react-native-community/eslint-config": "^3.2.0",
    "@total-typescript/ts-reset": "^0.3.7",
    "@types/lodash.has": "^4.5.7",
    "@types/lodash.set": "^4.3.7",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "autoprefixer": "^10.4.13",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-react-perf": "^3.3.1",
    "eslint-plugin-tailwindcss": "^3.10.1",
    "postcss": "^8.4.21",
    "prettier": "^2.8.4",
    "prettier-plugin-tailwindcss": "^0.2.7",
    "tailwindcss": "^3.2.7"
  }
}
```

next.config.js
```
const { withExpo } = require('@expo/next-adapter');

/** @type {import('next').NextConfig} */
const nextConfig = {
  swcMinify: true,
  transpilePackages: [
    'react-native',
    'nativewind',
  ],
  experimental: {
    forceSwcTransforms: true,
    fullySpecified: false,
    esmExternals: 'loose'
  },
  reactStrictMode: true,
  images: {
    unoptimized: true,
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.m?js$/,
      type: 'javascript/auto',
      resolve: {
        fullySpecified: false,
      },
    })
    return config
  },
};

module.exports = withExpo(nextConfig);
```

**Comment by natew** [comment]
Why aren’t you using the next plugin?

You need to alias react-native to react-native-web

**Comment by brianephraim** [comment]
Thank you very much. I got it to work.

I don't know if it has due to my particular NextJS setup, but the Tamagui documentation for NextJS setup was misleading by saying:

"For a minimal setup with just @tamagui/core, you can get away with this configuration: [shows minimal next.config]"

I did have to setup `@tamagui/next-plugin` in my next.config as you suggested, and is described here : https://tamagui.dev/docs/guides/next-js#nextconfigjs

But the `@tamagui/next-plugin` section says, "For a more complete configuration," and for me, it was mandatory.

I also had to setup TamaguiProvider as described on that linked docs page.
