### ISSUE TITLE
Unable to make Tamagui work on a managed Expo project

### ISSUE THREAD

**Issue by inakineitor** [tamagui/tamagui#112]
**Describe the bug**
I recently stumbled upon Tamagui. I believe it's a great system and wanted to style an upcoming React Native Expo app using it. So I followed all the instructions for React Native and Expo, but there seems to be a problem with the Tamagui.Provider component that I am not able to resolve.

**To Reproduce**
1. Install all the Tamagui packages and upgrade react-native-web to ^0.18.1 and react-native-safe-area-context ^4.3.1.
2. Add the following code to babel.config.js:
```
plugins: [
      'react-native-reanimated/plugin',
      [
        '@tamagui/babel-plugin',
        {
          components: ['tamagui'],
          config: './app/theme/tamagui-config.ts',
          logTimings: true,
          disableExtraction: process.env.NODE_ENV === 'development',
        },
      ],
      // be sure to set TAMAGUI_TARGET
      [
        'transform-inline-environment-variables',
        {
          include: 'TAMAGUI_TARGET',
        },
      ],
    ],
```
3. Create the following tamagui-config.ts file: 
```
import { createTamagui } from 'tamagui';
import { createInterFont } from '@tamagui/font-inter';
import { shorthands } from '@tamagui/shorthands';
import { themes, tokens } from '@tamagui/theme-base';
import { createAnimations } from '@tamagui/animations-reanimated';

const animations = createAnimations({
  bouncy: {
    type: 'spring',
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  lazy: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
  quick: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
});

const headingFont = createInterFont({
  size: {
    6: 15,
  },
  transform: {
    6: 'uppercase',
    7: 'none',
  },
  weight: {
    6: '400',
    7: '700',
  },
  color: {
    6: '$colorFocus',
    7: '$color',
  },
  letterSpacing: {
    5: 2,
    6: 1,
    7: 0,
    8: -1,
    9: -2,
    10: -3,
    12: -4,
    14: -5,
    15: -6,
  },
});

const bodyFont = createInterFont(
  {},
  {
    sizeSize: (size: number) => Math.round(size * 1.1),
    sizeLineHeight: (size: number) =>
      Math.round(size * 1.1 + (size > 20 ? 10 : 10)),
  },
);

const config = createTamagui({
  animations,
  defaultTheme: 'light',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
});

export type Conf = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;
```

4. Add provider to App.tsx:
```
import React, { useCallback, useEffect } from 'react';
import { StatusBar } from 'expo-status-bar';
import * as SplashScreen from 'expo-splash-screen';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import './localization/i18n';

import useCachedResources from './hooks/useCachedResources';
import useColorScheme from './hooks/useColorScheme';
import Navigation from './navigation';
import { View } from 'react-native';
import Tamagui from './theme/tamagui-config';

export default function App() {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();

  useEffect(() => {
    const preventSplashFromHiding = async () => {
      await SplashScreen.preventAutoHideAsync();
    };
    preventSplashFromHiding();
  }, []);

  const onLayoutRootView = useCallback(async () => {
    if (isLoadingComplete) {
      // This tells the splash screen to hide immediately! If we call this after
      // `setAppIsReady`, then we may see a blank screen while the app is
      // loading its initial state and rendering its first pixels. So instead,
      // we hide the splash screen once we know the root view has already
      // performed layout.
      await SplashScreen.hideAsync();
    }
  }, [isLoadingComplete]);

  if (!isLoadingComplete) {
    return null;
  }

  return (
    <SafeAreaProvider onLayout={onLayoutRootView}>
      <Tamagui.Provider disableInjectCSS defaultTheme="light"></Tamagui.Provider>
    </SafeAreaProvider>
  );
}
```
5. You will get this error every time the app starts: `TypeError: null is not an object (evaluating 'dispatcher.useMemo')`. Which makes it impossible for it to start. If, leaving all the rest of the files the same, you were to replace the provider with a simple view with text, the app runs perfectly.
6. 
**Environment (please complete the following information):**
 - OS: iOS 15.5 (Expo)
 - Version: ^1.0.1-beta.75

**Comment by ivopr** [comment]
Hey, not sure why it isn't working, but you can check [here](https://github.com/ivopr/tamagui-expo) and compare. Also note that Tamagui as of now requires RNScreens 4.2.5 and RNW 0.18, not the Expo SDK recommended.

**Comment by inakineitor** [comment]
Thanks for the prompt response! I recreated the problem by running `expo init` on a new project and just installing Tamagui. I followed the configuration as you had it in the repository that you shared. [Here](https://github.com/inakineitor/error-expo-tamagui) is the repository with that code.

The exact same error shows up inside the ThemeProvider. It seems to be related to the `useMemo` function inside the provider but I don't really understand what the problem is.

**Comment by ivopr** [comment]
@inakineitor you running in Expo Go or Dev Client? I'm getting an error related to RNSafeArea, since Expo Go was prob built with 4.2.4

**Comment by inakineitor** [comment]
I am running in Expo Go. Should I be running in the Dev Client? I assumed that Expo Go was okay because the repository you shared works perfectly in Expo Go.

I just ran `yarn start --clear` and this the error seems to be related to the use of some sort of hook within the `ThemeProvider`. There is a mention of RNSafeArea in the stack but I believe that is because there is a `SafeAreaProvider` inside the `ThemeProvider`. To my understanding, that shouldn't be the source of the issue.

I am currently using macOS Monterey on an Intel Macbook Pro with node v16.15.0 (nvm), Expo v5.4.12, and Yarn v1.22.18. I don't have another computer at hand right now so I cannot test on Windows and/or an M1 Mac.

Here is the full console log:
```
❯ yarn start --clear
yarn run v1.22.18
$ expo start --clear
› Port 19000 is running recyco-user-native-app in another window
  /Users/inakiarango/Documents/Work/Recyco/Repositories/Native Apps/recyco-user-native-app (pid 27307)
✔ Use port 19002 instead? … yes
Starting project at /Users/inakiarango/Documents/Work/Recyco/Repositories/error-expo-tamagui
Developer tools running on http://localhost:19004
Some dependencies are incompatible with the installed expo package version:
 - react-native-safe-area-context - expected version: 4.2.4 - actual version installed: 4.3.1
 - react-native-web - expected version: 0.17.7 - actual version installed: 0.18.1
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
or install individual packages by running expo install [package-name ...]
Starting Metro Bundler
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ██▀▀ ▀▄██ ▄▄▄▄▄ █
█ █   █ █  ▀█ ▀▄█▄█ █   █ █
█ █▄▄▄█ █▀  █▄▀▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█ ▀ █▄▄▄▄▄▄▄█
█▄ █▀  ▄▀██▄█▄▀▄ ▄▀█ ▀▄▄ ▄█
█▄▀ █▄▀▄▄█ ▄█▀██ █ █▀   ▀██
█ █ █ ▀▄ ▀█▀▄▀▀▄▀▄█▄ ▀▄ ▀██
███▀▄█▄▄▄▄▀█ ▄██ ▀▀ ██ ▀███
█▄▄▄▄██▄█▀ ▀█▄▀▄▀ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀ ▀█▀▄█▀ █▄█ ▀▀▀▀█
█ █   █ █▄█▀▄▀▄ █ ▄ ▄▄▀   █
█ █▄▄▄█ █▀▀▀ ▄ ▄▀█▀▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄▄▄█▄▄████▄▄▄▄▄▄▄█

› Metro waiting on exp://10.0.0.158:19002
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu
› Press d │ show developer tools
› shift+d │ toggle auto opening developer tools on startup (disabled)

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
Error: ENOENT: no such file or directory, scandir '/Users/inakiarango/Documents/Work/Recyco/Repositories/error-expo-tamagui/assets/icons'
iOS Bundling JavaScript [==================================iOS Bundling JavaScript [==================================iOS Bundling JavaScript [==================================
iOS Bundling complete 178440ms
iOS Running app on Iñaki

ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
at node_modules/react-native/index.js:470:4 in module.exports.get__ViewPropTypes
at node_modules/@react-native-community/blur/src/BlurView.ios.js:28:6 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/@react-native-community/blur/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/tamagui/dist/cjs/views/BlurView.native.js:23:25 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/tamagui/dist/cjs/index.js:162:31 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at app/tamagui.config.ts:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at app/App.tsx:8:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
at http://10.0.0.158:19002/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:369630:3 in global code

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:209:4 in printWarning
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:183:18 in error
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:1592:11 in resolveDispatcher
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:1649:36 in useMemo
at node_modules/@tamagui/core/dist/cjs/views/ThemeProvider.js:49:23 in ThemeProvider
at node_modules/expo-font/build/FontHooks.js:26:33 in loadAsync.then$argument_0

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:209:4 in printWarning
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:183:18 in error
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:1592:11 in resolveDispatcher
at node_modules/@tamagui/core/node_modules/react/cjs/react.development.js:1649:36 in useMemo
at node_modules/@tamagui/core/dist/cjs/views/ThemeProvider.js:49:23 in ThemeProvider
at node_modules/expo-font/build/FontHooks.js:26:33 in loadAsync.then$argument_0

TypeError: null is not an object (evaluating 'dispatcher.useMemo')

This error is located at:
    in _ThemeProvider
    in _TextAncestorProvider
    in TamaguiProvider
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in _SafeAreaProvider
    in Unknown (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:4 in showErrorDialog
at node_modules/expo-font/build/FontHooks.js:26:33 in loadAsync.then$argument_0
```

**Comment by ivopr** [comment]
Noted some missing libs on your package.json, might not be the solution to this, but it'll bite your back later, here is all Tamagui related libs (the ones I've already had problems with, since they were missing) you should have
```
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "~3.11.1",
    "react-native-svg": "12.3.0",
    "react-native-web": "^0.18",
```
You could also check if you got multiple react versions installed (yarn why react). Other than that I've really have no clue as to what is happening.

**Comment by inakineitor** [comment]
Check out the new commit to the repo. I added all those dependencies but that didn't seem to fix the problem.

You were spot on with the React version, though. I ran `yarn why react` and there were two versions present. React 17 coming with Expo, and React 18 required by `tamagui` and `@tamagui/core`.

I believe the problem is caused by a mismatch of React versions used between Tamagui and the rest of the App, which leads to the React environment within Tamagui not being detected, thus throwing the "You cannot use hooks outside a component" error.

I don't think the error is caused by not using React 18, since the repository you sent uses React 17 and works perfectly.

The question remaining now is: How do I install Tamagui so that it depends on React 17 and not React 18?

**Comment by ivopr** [comment]
You can use the `resolutions` field on `package.json`. React 18 introduced a bunch of things not backwards compatible, I think Tamagui still doesnt fully support it too. This should do the trick
```
  "resolutions": {
    "@types/react": "17.0.21",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native-web": "^0.18"
  },
```

**Comment by inakineitor** [comment]
Perfect! Thank you so much.

I don't know if it's you or @natew that is writing the Expo guide for the website, but I think this should be mentioned since the resolutions are not added by default by Expo when you create a project.

Good night!

**Comment by natew** [comment]
@ivopr thanks for taking the lead here, huge help!

@inakineitor this is a great thread to improve the docs. I'll incorporate it soon.

**Comment by natew** [comment]
Added some basic docs here: e2fd7e5ce5c72203243de98880e86dd89bae0217
