### ISSUE TITLE
Can't start up a newly created project from `npm create tamagui`

### ISSUE THREAD

**Issue by mrfullset** [tamagui/tamagui#1181]
### Current Behavior

After `yarn native` I've scanned QR code with `Expo Go` on Pixel 4a and got the following error:

```
Logs for your project will appear below. Press Ctrl+C to exit.
Error: ENOENT: no such file or directory, scandir '/Users/username/Programming/projectname/apps/expo/assets/images'
Error: Unable to resolve module ./node_modules/expo/AppEntry from /Users/username/Programming/projectname/apps/expo/.: 

None of these files exist:
  * node_modules/expo/AppEntry(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules/expo/AppEntry/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/username/Programming/projectname/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/username/Programming/projectname/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at /Users/username/Programming/projectname/node_modules/metro/src/lib/transformHelpers.js:177:21
    at Server._resolveRelativePath (/Users/username/Programming/projectname/node_modules/metro/src/Server.js:1161:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/username/Programming/projectname/node_modules/metro/src/Server.js:468:37)
    at async Server._processRequest (/Users/username/Programming/projectname/node_modules/metro/src/Server.js:390:9)

```

### Expected Behavior

App should start.

### Tamagui Version

```markdown
1.28.0
```

### Reproduction

```markdown
npm create tamagui
cd projectname
yarn native
Scan QR with ExpoGo app
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 914.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.4
  npmPackages:
    @react-navigation/native: ^6.1.6 => 6.1.6 
    burnt: ^0.10.0 => 0.10.0 
    expo-router: ^1.4.3 => 1.7.0 
    react-native: ^0.71.4 => 0.71.7 
    react-native-gesture-handler: ^2.9.0 => 2.9.0 
    react-native-safe-area-context: ^4.5.2 => 4.5.2 
    react-native-screens: ^3.20.0 => 3.20.0 
    react-native-svg: 13.4.0 => 13.4.0
```

**Comment by mrfullset** [comment]
OK, I've solved the issue by removing `runtimeVersion` section from `apps/expo/app.json`.

Original solution: https://github.com/expo/expo/issues/17461#issuecomment-1156131763
