### ISSUE TITLE
All <Adapt> dependent renders fail in tests (native)

### ISSUE THREAD

**Issue by techilluminati** [tamagui/tamagui#1253]
### Current Behavior

`TypeError: Cannot create proxy with a non-object as target or handler`

Adapt:73 -> web/useMedia:199
stack trace:
```
      at ../../.yarn/__virtual__/@tamagui-web-virtual-5a751695ac/0/cache/@tamagui-web-npm-1.30.21-4bf573f5b9-c745059ad2.zip/node_modules/@tamagui/web/src/hooks/useMedia.tsx:199:12
      at mountMemo (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7224:19)
      at Object.useMemo (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7644:16)
      at useMemo (../../.yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip/node_modules/react/cjs/react.development.js:1650:21)
      at useMedia (../../.yarn/__virtual__/@tamagui-web-virtual-5a751695ac/0/cache/@tamagui-web-npm-1.30.21-4bf573f5b9-c745059ad2.zip/node_modules/@tamagui/web/src/hooks/useMedia.tsx:198:10)
      at Adapt2 (../../.yarn/cache/@tamagui-adapt-npm-1.30.21-884bad579c-03d579858c.zip/node_modules/@tamagui/adapt/src/Adapt.tsx:73:19)
      at renderWithHooks (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6351:18)
      at mountIndeterminateComponent (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9855:13)
      at beginWork (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11312:16)
      at performUnitOfWork (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15811:12)
      at workLoopSync (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15745:5)
      at renderRootSync (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15717:7)
      at performSyncWorkOnRoot (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15422:20)
      at flushSyncCallbacks (../../.yarn/__virtual__/react-test-renderer-virtual-5e4009100f/0/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushActQueue (../../.yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip/node_modules/react/cjs/react.development.js:2667:24)
      at Object.act (../../.yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip/node_modules/react/cjs/react.development.js:2521:11)
      at act (../../.yarn/__virtual__/@testing-library-react-native-virtual-b167b7c858/0/cache/@testing-library-react-native-npm-12.1.2-e04dd4c980-912fc961f2.zip/node_modules/@testing-library/react-native/src/render-act.ts:13:16)
      at render (../../.yarn/__virtual__/@testing-library-react-native-virtual-b167b7c858/0/cache/@testing-library-react-native-npm-12.1.2-e04dd4c980-912fc961f2.zip/node_modules/@testing-library/react-native/src/render.tsx:48:33)
      at render (src/render.tsx:16:18)
      at Object.<anonymous> (src/ReadMoreBox.spec.tsx:13:22)
      
      ```
      
      Even adding explicit calls to `configureMedia` in jest tests do not resolve undefined initStates
      
      ```
      import { configureMedia } from '@tamagui/web';
import { config } from './tamagui.config';

describe('ReadMoreBox', () => {
  beforeEach(() => {
    configureMedia(config);
  });
  ```

### Tamagui Version

```markdown
latest
```

### Reproduction

```markdown
get jest online. standard enterprise.
```

**Comment by techilluminati** [comment]
Solution patch:
```
-let initState;
+let initState = {};
```
I believe the core issue is that web is getting called from Adapt when we're in mobile perspectives.

**Comment by natew** [comment]
you aren't calling createTamagui before you run your render somehow
