### ISSUE TITLE
next/font/local issue on versions greater than 1.29.0

### ISSUE THREAD

**Issue by vstlouis** [tamagui/tamagui#1309]
### Current Behavior

When using next/font/local I receive a "Tamagui Webpack Loader Error:" on versions greater than 1.29.0.

The breaking code is located [here](https://github.com/vstlouis/tamagui-next-font-local-repro/blob/main/packages/ui/src/fonts.ts).

This should not work for you as the version is set to 1.29.1. You can then downgrade to 1.29.0 to see that the application works

dont forget to install after downgrading the package and also to remove the cache files at `apps/next/.tamagui`

```markdown
Tamagui Webpack Loader Error:
   createCSSVariable expected string: undefined
Error: createCSSVariable expected string: undefined
    at createCSSVariable (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/node_modules/@tamagui/core-node/dist/index.js:5850:17)
    at variableToCSS (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/node_modules/@tamagui/core-node/dist/index.js:40172:63)
    at /Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/node_modules/@tamagui/core-node/dist/index.js:40643:78
    at createTamagui (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/node_modules/@tamagui/core-node/dist/index.js:40715:9)
    at loadTamagui (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:67:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.load [as loadTamagui] (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:88:42)
    at async extractToClassNames (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/tamagui-loader/dist/cjs/loader.js:69:23)

Tamagui Webpack Loader Error:
   Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'Consumer' -> object with constructor 'Object'
    --- property '_context' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'Consumer' -> object with constructor 'Object'
    --- property '_context' closes the circle
    at JSON.stringify (<anonymous>)
    at parseWithConfig (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:184:18)
    at Object.parse (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:107:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async extractToClassNames (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:93:15)
    at async Object.loader2 (/Users/stlouis/code/src/github.com/tamagui/next-font-issue/node_modules/tamagui-loader/dist/cjs/loader.js:69:23)
```

### Expected Behavior

Expected next's not to crash on boot

### Tamagui Version

```markdown
1.29.1
```

### Reproduction

```markdown
https://github.com/vstlouis/tamagui-next-font-local-repro/tree/main
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.24 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/1785_1685976473508/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/1785_1685976473508/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.4
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.22.5
    @manypkg/cli: ^0.19.1 => 0.19.2
    check-dependency-version-consistency: ^3.0.3 => 3.3.0
    eslint: ^8.21.0 => 8.43.0
    node-gyp: ^9.3.1 => 9.4.0
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.10.3 => 1.10.3
    typescript: ^5.1.3 => 5.1.3
```

**Comment by natew** [comment]
the very latest tamagui outputs a better error message, if you can run with DEBUG=tamagui as well and put the logs here
