### ISSUE TITLE
[Issue] react-native run-android returns error `Unexpected token 'export'`

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1349]
### Current Behavior

When I run `react-native run-android`, I see Tamagui warnings
```
transform[stdout]: ⚠️ Tamagui Warning [001]: Skipping loading @hackily/tamagui-ds-repro due to error bundling.
transform[stdout]:    - message: Unexpected token 'export'
transform[stdout]:    - for more info see: https://tamagui.dev/docs/intro/errors#warning-001
transform[stdout]:    - set TAMAGUI_SHOW_FULL_BUNDLE_ERRORS=1 to see stack trace
transform[stderr]: Warning: Tamagui didn't find any valid components (DEBUG=tamagui for more)
```

If I pass `TAMAGUI_SHOW_FULL_BUNDLE_ERRORS=1` then I see this

```
transform[stderr]: Tamagui failed loading the pre-built tamagui.config.ts
transform[stderr]:   
transform[stderr]:   Unexpected token 'export'
transform[stderr]:   /Users/neilwang/Documents/git/react69/node_modules/@hackily/tamagui-ds-repro/core/index.ts:1
transform[stderr]: export * from "./tamagui.config";
transform[stderr]: ^^^^^^
transform[stderr]: 
transform[stderr]: SyntaxError: Unexpected token 'export'
transform[stderr]:     at internalCompileFunction (node:internal/vm:73:18)
transform[stderr]:     at wrapSafe (node:internal/modules/cjs/loader:1175:20)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1219:27)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
transform[stderr]:     at Object.newLoader [as .ts] (/Users/neilwang/Documents/git/react69/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1113:32)
transform[stderr]:     at Module._load (node:internal/modules/cjs/loader:960:12)
transform[stderr]:     at Module.require (node:internal/modules/cjs/loader:1137:19)
transform[stderr]:     at Module.tamaguiRequire [as require] (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/require.js:74:20)
transform[stderr]:     at require (node:internal/modules/helpers:121:18)
transform[stderr]:     at attemptLoad (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:237:32)
transform[stderr]:     at /Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:248:21
transform[stderr]:     at Array.flatMap (<anonymous>)
transform[stderr]:     at loadComponents (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:213:36)
transform[stderr]:     at loadTamaguiSync (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:103:65)
transform[stderr]:     at loadSync (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:91:81)
transform[stderr]:     at Object.parseSync (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:110:28)
transform[stderr]:     at PluginPass.enter (/Users/neilwang/Documents/git/react69/node_modules/@tamagui/babel-plugin/dist/cjs/index.js:91:23)
transform[stderr]:     at newFn (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/visitors.js:153:14)
transform[stderr]:     at NodePath._call (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/path/context.js:46:20)
transform[stderr]:     at NodePath.call (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/path/context.js:36:17)
transform[stderr]:     at NodePath.visit (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/path/context.js:82:31)
transform[stderr]:     at TraversalContext.visitQueue (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/context.js:86:16)
transform[stderr]:     at TraversalContext.visitSingle (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/context.js:65:19)
transform[stderr]:     at TraversalContext.visit (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/context.js:109:19)
transform[stderr]:     at traverseNode (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
transform[stderr]:     at traverse (/Users/neilwang/Documents/git/react69/node_modules/@babel/traverse/lib/index.js:49:34)
transform[stderr]:     at transformFile (/Users/neilwang/Documents/git/react69/node_modules/@babel/core/lib/transformation/index.js:81:29)
transform[stderr]:     at transformFile.next (<anonymous>)
transform[stderr]:     at run (/Users/neilwang/Documents/git/react69/node_modules/@babel/core/lib/transformation/index.js:24:12)
transform[stderr]:     at run.next (<anonymous>)
transform[stderr]:     at /Users/neilwang/Documents/git/react69/node_modules/@babel/core/lib/transform-ast.js:23:41
transform[stderr]:     at Generator.next (<anonymous>)
transform[stderr]:     at evaluateSync (/Users/neilwang/Documents/git/react69/node_modules/gensync/index.js:251:28)
transform[stderr]:     at sync (/Users/neilwang/Documents/git/react69/node_modules/gensync/index.js:89:14)
transform[stderr]:     at stopHiding - secret - don't use this - v1 (/Users/neilwang/Documents/git/react69/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:46:12)
transform[stderr]:     at transformFromAstSync (/Users/neilwang/Documents/git/react69/node_modules/@babel/core/lib/transform-ast.js:44:83)
transform[stderr]:     at Object.transform (/Users/neilwang/Documents/git/react69/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-react-native-babel-transformer/src/index.js:192:20)
transform[stderr]:     at transformJSWithBabel (/Users/neilwang/Documents/git/react69/node_modules/metro-transform-worker/src/index.js:398:45)
transform[stderr]:     at Object.transform (/Users/neilwang/Documents/git/react69/node_modules/metro-transform-worker/src/index.js:571:18)
transform[stderr]:     at Object.transform (/Users/neilwang/Documents/git/react69/node_modules/metro/src/DeltaBundler/Worker.js:38:36)
transform[stderr]:     at execFunction (/Users/neilwang/Documents/git/react69/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js:137:17)
transform[stderr]:     at execHelper (/Users/neilwang/Documents/git/react69/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js:116:5)
transform[stderr]:     at execMethod (/Users/neilwang/Documents/git/react69/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js:120:5)
transform[stderr]:     at process.messageListener (/Users/neilwang/Documents/git/react69/node_modules/metro/node_modules/jest-worker/build/workers/processChild.js:38:7)
transform[stderr]:     at process.emit (node:events:511:28)
transform[stderr]:     at emit (node:internal/child_process:944:14)
transform[stderr]:     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
transform[stderr]:   
transform[stderr]:   You can see if it loads in the node repl:
transform[stderr]:   
transform[stderr]:   require("./@hackily/tamagui-ds-repro").default
```

### Expected Behavior

I should be able to do an android build without these warnings, and do a release build without the app crashing.

### Tamagui Version

```markdown
1.36.2
Happens with the latest too though.
```

### Reproduction

```markdown
> git clone https://github.com/hackily/tamagui-react-69-repro
> cd tamagui-react-69-repro
> yarn
> yarn android
```

And app will crash if running release
```
> yarn android:release
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 92.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.4
  npmPackages:
    @babel/core: ^7.12.9 => 7.22.5 
    @babel/runtime: ^7.12.5 => 7.22.5 
    @hackily/tamagui-ds-repro: https://github.com/hackily/tamagui-ds-repro.git#0.0.1 => 0.0.1 
    @react-native-community/cli: ^8.0.4 => 8.0.7 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @tamagui/babel-plugin: ^1.36.2 => 1.36.4 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4 
    eslint: ^7.32.0 => 7.32.0 
    jest: ^26.6.3 => 26.6.3 
    metro-react-native-babel-preset: ^0.70.3 => 0.70.4 
    react: 18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-native: 0.69.11 => 0.69.11 
    react-test-renderer: 18.0.0 => 18.0.0 
    tamagui: ^1.36.2 => 1.36.4
```

**Comment by TheEhsanSarshar** [comment]
you need to have build artifacts inside `https://github.com/hackily/tamagui-ds-repro`

**Comment by hackily** [comment]
I apologize in advance, I'm not very seasoned with react native. How might I ask Metro to bundle the package for me?

**Comment by hackily** [comment]
Thanks, I didn't end up figuring out how to bundle with metro, but I'm transpiling all the code in my package.
I agree a monorepo is better in most instances, but internally we want a little more flexibility to choose which version of the design system we want to consume
