### ISSUE TITLE
create-tamagui-app build error

### ISSUE THREAD

**Issue by pontusab** [tamagui/tamagui#147]
I discovered this bug in my repo but after running a fresh install with `create-tamagui-app` I have the same problem.

**To Reproduce**
1. run `npx create-tamagui-app`
2. Go to `next` and run `yarn build`

Output:

```
 ssr  | withTamagui skipping resolving @gorhom/bottom-sheet$
 web  | withTamagui skipping resolving @gorhom/bottom-sheet$
 ssr  | withTamagui skipping resolving @gorhom/bottom-sheet$
      | patched  dist/modules/createDOMProps/index.js
      | patched  dist/cjs/modules/createDOMProps/index.js
  1️⃣  Inline optimized  2️⃣  Inline flattened  3️⃣  styled() extracted
      |                          total ·  1️⃣  ·  2️⃣  ·  3️⃣
 web  |                    screen   12 ·   7 ·   5 ·   0  171ms ⚠️ 
 web  |             detail-screen    3 ·   2 ·   1 ·   0   30ms  
 web  |               MyComponent    0 ·   0 ·   0 ·   1   15ms  
 web  |                     Input    0 ·   0 ·   0 ·   1    7ms  
 web  |                  Fieldset    0 ·   0 ·   0 ·   1    7ms  
 web  |                     Group    0 ·   0 ·   0 ·   1   25ms  
 web  |                  TextArea    0 ·   0 ·   0 ·   1    6ms  
 web  |                      Form    0 ·   0 ·   0 ·   1    4ms  
 web  |              EnsureFlexed    0 ·   0 ·   0 ·   1    2ms  
 web  |            VisuallyHidden    0 ·   0 ·   0 ·   1    9ms  
 web  |                   Layouts    0 ·   0 ·   0 ·   7    5ms  
 web  |                    Avatar    0 ·   0 ·   0 ·   2   19ms  
 web  |                      Card    0 ·   0 ·   0 ·   4   21ms  
 web  |                    Select    0 ·   0 ·   0 ·   4   37ms  
 web  |                  ListItem    0 ·   0 ·   0 ·   3   11ms  
 web  |                    Square    0 ·   0 ·   0 ·   1    3ms  
 web  |                    Circle    0 ·   0 ·   0 ·   1    2ms  
 web  |                    Button    0 ·   0 ·   0 ·   2   12ms  
info  - Creating an optimized production build .Error: Unexpected token 'export'
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader (/Users/pontus/Desktop/test/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/pontus/Desktop/test/node_modules/esbuild-register/dist/node.js:4801:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ChildProcess.listener (/Users/pontus/Desktop/test/node_modules/@tamagui/static/dist/cjs/extractor/getStaticBindingsForScope.js:68:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 57.60 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.1

**Comment by pontusab** [comment]
If I pass an empty array to `importsWhitelist` instead of the default:

`importsWhitelist: ['constants.js', 'colors.js']`

it now build successfully!

```
const transform = withPlugins([
  withTM([
    'solito',
    'react-native-web',
    'expo-linking',
    'expo-constants',
    'expo-modules-core',
    '@my/config',
  ]),
  withTamagui({
    config: './tamagui.config.ts',
    components: ['tamagui', '@my/ui'],
    importsWhitelist: [], <--- this
    logTimings: true,
    disableExtraction,
    shouldExtract: (path) => {
      if (path.includes('packages/app')) {
        return true
      }
    },
    excludeReactNativeWebExports: [
      'Switch',
      'ProgressBar',
      'Picker',
      'Modal',
      'VirtualizedList',
      'VirtualizedSectionList',
      'AnimatedFlatList',
      'FlatList',
      'CheckBox',
      'Touchable',
      'SectionList',
    ],
  }),
])
```

**Comment by natew** [comment]
Yea that's a good solution for now, I'm working on a patch I can replicate.

**Comment by natew** [comment]
Fixed temporarily, it errors gracefully now. It's only happening for me in the starter repo not in a couple others, so I'll have to hunt down the diff.
