### ISSUE TITLE
Tamagui + Expo (Expo router v2) - Cannot run Tamagui Web 

### ISSUE THREAD

**Issue by dipeshparashar** [tamagui/tamagui#1548]
### Current Behavior

I have been trying to run Tamagui on web within an Expo project with Expo router v2.  While the set-up did run on iOS. I am unable to run to on web. I do not want to use Next. No Intention to test it on Android currently. 

The errors keep changing. It just never runs. The projects runs completely fine without Tamagui and its dependencies. 

Error 1: Why is it looking for Android components when i am not even trying to run Android Simulator 
```
None of these files exist:
  * node_modules/react-native/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css)
  * node_modules/react-native/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid/index(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
     |                                         ^
  18 | import typeof FlatList from './Libraries/Lists/FlatList';
  19 | import typeof Image from './Libraries/Image/Image';
  20 | import typeof ImageBackground from './Libraries/Image/ImageBackground';
    at ModuleResolver.resolveDependency (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/user99/Documents/Newapp/App/2023/Tamagui/newexpoapp/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
› Stopped server
user99Macbook:newexpoapp user99$ 
```

Error 2
```
None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css)
  12 | import type {ExtendedExceptionData} from './Data/parseLogBoxLog';
  13 |
> 14 | import Platform from '../Utilities/Platform';
     |                       ^
  15 | import RCTLog from '../Utilities/RCTLog';
  16 |
  17 | export type {LogData, ExtendedExceptionData, IgnorePattern};
    at ModuleResolver.resolveDependency (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 14)
    at async Graph._processModule (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/user99/Documents/NewApp/App/2023/Tamagui/newappexpo/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
```

### Expected Behavior

There is no content or components yet. Just the bare minimum project should run. 

### Tamagui Version

```markdown
^1.52.6
```

### Reproduction

```markdown
1. Create Expo Router project using this guide: https://docs.expo.dev/routing/installation/ 
2. Add Tamagui to this existing project using this guide: https://stackoverflow.com/questions/75154160/integrate-tamagui-with-existing-expo-react-native-app
3. Try to run on the web.
```

### System Info

```markdown
OS: Mac Monterey 12.6 
IDE: VSCode



Package.json

{
  "name": "newappexpo",
  "main": "expo-router/entry",
  "scheme": "newappexpo",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-picker/picker": "2.4.10",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.0.2",
    "@tamagui/animations-react-native": "^1.52.6",
    "@tamagui/babel-plugin": "^1.52.6",
    "@tamagui/config": "^1.52.6",
    "@tamagui/font-inter": "^1.52.6",
    "@tamagui/shorthands": "^1.52.6",
    "@tamagui/themes": "^1.52.6",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "expo": "~49.0.5",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.72.3",
    "react-native-canvas": "^0.1.39",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-modal-picker": "^0.0.16",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-web": "^0.19.7",
    "react-native-webview": "^13.3.1",
    "tamagui": "^1.52.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "overrides": {
    "react-refresh": "~0.14.0"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  },
  "private": true
}
```

Tamagui Config:
```
import { createInterFont } from '@tamagui/font-inter';
import { createMedia } from '@tamagui/react-native-media-driver';
import { shorthands } from '@tamagui/shorthands';
import { themes, tokens } from '@tamagui/themes';
import { createTamagui } from 'tamagui';
import { createAnimations } from '@tamagui/animations-react-native';

const animations = createAnimations({
  bouncy: {
    type: 'spring',
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  lazy: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
  quick: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  }
});
const headingFont = createInterFont();
const bodyFont = createInterFont();
const config = createTamagui({
  animations,
  defaultTheme: 'dark',
  shouldAddPrefersColorThemes: false,
  themeClassNameOnRoot: false,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens,
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  })
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  // overrides TamaguiCustomConfig so your custom types
  // work everywhere you import `tamagui`
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
```

Babel.config
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      // Required for expo-router
      'expo-router/babel',
      'react-native-reanimated/plugin',
      ['@tamagui/babel-plugin', {
        components: ['tamagui'],
        config: './tamagui.config.ts',
        logTimings: true
      }],
      ['transform-inline-environment-variables', {
        include: 'TAMAGUI_TARGET',
      }]
    ],
  };
};

```

Metro Config:
```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  // [Web-only]: Enables CSS support in Metro.
  isCSSEnabled: true,
});

module.exports = config;

```

**Comment by natew** [comment]
new version bundles things in a much more friendly way, and for a repro i really need something i can just "run" so its easy for me, so closing this but i bet >= 1.62 should work seamlessly.
