### ISSUE TITLE
Error during generating of new project with npm create tamagui@latest

### ISSUE THREAD

**Issue by tonven** [tamagui/tamagui#1723]
### Current Behavior

When generation new project with `npm create tamagui@latest` I am getting error. I tried different versions of node. I tried to install promise-spawn globally manually. Still does not work. Error:

```
$ git init
[tamagui] Failed to copy example into C:\dev\test\temp\test

 ProcessOutput {
  stdout: '',
  stderr: '',
  signal: null,
  exitCode: 1
}
node:child_process:965
    throw err;
    ^

Error: Command failed: node C:\Users\tonven\AppData\Local\npm-cache\_npx\d01fabec74a282ea\node_modules\create-tamagui\dist\index.js
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at Object.<anonymous> (C:\Users\tonven\AppData\Local\npm-cache\_npx\d01fabec74a282ea\node_modules\create-tamagui\run.js:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21836,
  stdout: null,
  stderr: null
}

Node.js v18.18.0
npm ERR! code 1
npm ERR! path C:\dev\test\temp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-tamagui

npm ERR! A complete log of this run can be found in: C:\Users\tonven\AppData\Local\npm-cache\_logs\2023-09-28T16_15_52_619Z-debug-0.log
```

**Error from log file:**

```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\tonven\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.1.0
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\tonven\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\dev\test\temp\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\tonven\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\tonven\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm create tamagui@latest
22 verbose argv "create" "tamagui@latest"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:C:\Users\tonven\AppData\Local\npm-cache\_logs\2023-09-28T16_15_52_619Z-
26 verbose logfile C:\Users\tonven\AppData\Local\npm-cache\_logs\2023-09-28T16_15_52_619Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 33ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 http fetch GET 200 https://registry.npmjs.org/create-tamagui 794ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:create Completed in 10401ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (C:\Users\tonven\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:517:28)
38 verbose stack     at maybeClose (node:internal/child_process:1098:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
39 verbose cwd C:\dev\test\temp
40 verbose Windows_NT 10.0.22621
41 verbose node v18.18.0
42 verbose npm  v10.1.0
43 error code 1
44 error path C:\dev\test\temp
45 error command failed
46 error command C:\Windows\system32\cmd.exe /d /s /c create-tamagui
47 verbose exit 1
48 timing npm Completed in 10621ms
49 verbose code 1
50 error A complete log of this run can be found in: C:\Users\tonven\AppData\Local\npm-cache\_logs\2023-09-28T16_15_52_619Z-debug-0.log
```

### Expected Behavior

Generating of new project happens without error

### Tamagui Version

```markdown
1.72.3
```

### Platform (Web, iOS, Android)

```markdown
Windows 10
```

### Reproduction

```markdown
npm create tamagui@latest
```

### System Info

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 46.59 GB / 63.14 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
```

**Comment by natew** [comment]
Tamagui doesn't use promise-spawn anywhere at all...

**Comment by tonven** [comment]
@natew the error comes from this line: await $`git init`. Git init is working correctly if I run it manually from console. I see you have "git --version" before, and it does not failing, so the problem is not with my local instance of git

**Comment by tonven** [comment]
Tried `yarn create` at it gives the same error. If I try generating template without git, everything works as expected. Right after I can just run git init and I don't get any errors.

**Comment by natew** [comment]
You're the only one getting this error for some reason, we've tried on quite a few machines and no one else reporting it despite a few hundred creations a day. Maybe your git or node or something has something messed up in how its set up :/

**Comment by tonven** [comment]
> You're the only one getting this error for some reason, we've tried on quite a few machines and no one else reporting it despite a few hundred creations a day. Maybe your git or node or something has something messed up in how its set up :/

Sounds fair enough :) It is still not critical, maybe something is messed with my configuration on Windows machine. Thank you.

**Comment by kampgen** [comment]
I got the exact same error:
```
[tamagui] Failed to copy example into /Users/kampgen/Documents/Altas/Projeto/tamagui-reference

 Error: Command failed: git clone --branch master --depth 1 --sparse --filter=blob:none git@github.com:tamagui/tamagui.git "/Users/kampgen/.tamagui/tamagui/tamagui.git"
    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at exec (/Users/kampgen/.config/yarn/global/node_modules/create-tamagui/dist/index.js:31768:89)
    at setupTamaguiDotDir (/Users/kampgen/.config/yarn/global/node_modules/create-tamagui/dist/index.js:31802:56)
    at async setupTamaguiDotDir (/Users/kampgen/.config/yarn/global/node_modules/create-tamagui/dist/index.js:31829:75)
    at async cloneStarter (/Users/kampgen/.config/yarn/global/node_modules/create-tamagui/dist/index.js:31772:218)
    at async run (/Users/kampgen/.config/yarn/global/node_modules/create-tamagui/dist/index.js:32209:5) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 14235,
  stdout: null,
  stderr: null
}
error Command failed.
Exit code: 1
Command: /Users/kampgen/.yarn/bin/create-tamagui
Arguments: 
Directory: /Users/kampgen/Documents/Altas/Projeto
Output:
```

I tried with npm and yarn when using create tamagui, both failing. I'm using a MacOS, Node 21 and yarn with corepack.

**Comment by johnyfernandes** [comment]
Just got the same exact error when trying to run `bunx create-tamagui-app@latest` 
```
Creating tamagui app...
✔ Project name: … jtamagui

Creating a new tamagui app /Users/john/Downloads/Dev/Aplicações/Random/jtamagui...
jtamagui folder created.
Setting up /Users/john/.tamagui...
$ cd /private/tmp/create-tamagui-app@latest--bunx
$ cd /Users/john/.tamagui
Updating tamagui starters repo
$ git sparse-checkout set starters
De https://github.com/tamagui/tamagui
 * branch            master     -> FETCH_HEAD
$ git pull --rebase --allow-unrelated-histories --depth 1 origin master
Missing template for next-expo-solito in /Users/john/.tamagui/tamagui/starters/next-expo-solito
node:child_process:965
    throw err;
    ^

Error: Command failed: node /private/tmp/create-tamagui-app@latest--bunx/node_modules/create-tamagui-app/dist/index.js
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at Object.<anonymous> (/private/tmp/create-tamagui-app@latest--bunx/node_modules/create-tamagui-app/run.js:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 41282,
  stdout: null,
  stderr: null
}

Node.js v20.8.1
```

**Comment by giornn0** [comment]
> **EDIT: For anyone with the same issue, just run `bunx create-tamagui`, no `@latest` or anything, it worked for me.**

Yep, this worked for me with yarn too.

**Comment by nimeshmaharjan1** [comment]
still having this issue

[tamagui] Failed to copy example into C:\Users\mahar\projects\web

 Error: Command failed: git sparse-checkout set code

**Comment by AtanasChachev** [comment]
I was experiencing the same, no matter the node version (v18, v20) etc on MacOS.
I did fix this problem by:

```
1. cd /Users/${username}/.tamagui
2. git init
```

And that's all ... after that `npm create tamagui@latest` didn't give the error that was described by the issue owner.
