### ISSUE TITLE
npm create tamagui-app@latest crashes

### ISSUE THREAD

**Issue by hlynurstef** [tamagui/tamagui#191]
**Describe the bug**

The command crashes due to the git error `fatal: refusing to merge unrelated histories`

`npm create tamagui-app@latest`

Output:
```
Creating tamagui app...
✔ What is your project named? … tamagui-test-app

Creating a new tamagui app /Users/hlynur/projects/tamagui-test-app...
tamagui-test-app folder created.
Setting up /Users/hlynur/.tamagui...
$ cd /Users/hlynur/.tamagui
Updating tamagui starters repo
$ cd /Users/hlynur/.tamagui/tamagui
$ git sparse-checkout set starters
$ git pull --depth 1 origin master
From https://github.com/tamagui/tamagui
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
[tamagui] Failed to copy example into /Users/hlynur/projects/tamagui-test-app

 ProcessOutput {
  stdout: '',
  stderr: 'From https://github.com/tamagui/tamagui\n' +
  ' * branch            master     -> FETCH_HEAD\n' +
  'fatal: refusing to merge unrelated histories\n',
  signal: null,
  exitCode: 128 (Invalid exit argument)
}
node:child_process:905
    throw err;
    ^

Error: Command failed: node /Users/hlynur/.npm/_npx/99906ff8f8e870b9/node_modules/create-tamagui-app/dist/index.js
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at Object.<anonymous> (/Users/hlynur/.npm/_npx/99906ff8f8e870b9/node_modules/create-tamagui-app/run.js:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9698,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/hlynur/projects
npm ERR! command failed
npm ERR! command sh -c create-tamagui-app

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hlynur/.npm/_logs/2022-09-07T21_21_34_327Z-debug-0.log
```

**To Reproduce**

run the following command:

`npm create tamagui-app@latest`

**Comment by salman-ar-sar** [comment]
@natew Getting a similiar issue on the latest version. Not sure if related, so commenting here.

```
▀█▀ ▄▀█ █▀▄▀█ ▄▀█ █▀▀ █ █ █
 █  █▀█ █ ▀ █ █▀█ █▄█ █▄█ █

Creating tamagui app...
✔ Project name: … tamagui-test
✔ Pick a template: › Next + Expo + Solito (recommended for production) - Production-ready universal app with a monorepo.


Creating a new tamagui app /Users/salman/Developer/ReactNative/tamagui-test...
tamagui-test folder created.
✔ Do you want to use git? … yes

Setting up /Users/salman/.tamagui/tamagui/tamagui.git...
$ cd /Users/salman/.tamagui

Updating tamagui starters repo


$ git sparse-checkout set starters
From https://github.com/tamagui/tamagui
 * branch            master     -> FETCH_HEAD

$ git pull --rebase --allow-unrelated-histories --depth 1 origin master

Copying starter from /Users/salman/.tamagui/tamagui/tamagui.git/starters/next-expo-solito into tamagui-test...

[tamagui] Failed to copy example into /Users/salman/Developer/ReactNative/tamagui-test

 [Error: ENOENT: no such file or directory, lstat '/Users/salman/.tamagui/tamagui/tamagui.git/starters/next-expo-solito'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/salman/.tamagui/tamagui/tamagui.git/starters/next-expo-solito'
}
node:child_process:960
    throw err;
    ^

Error: Command failed: node /Users/salman/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/dist/index.js
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/salman/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/run.js:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 73290,
  stdout: null,
  stderr: null
}

Node.js v20.4.0
npm ERR! code 1
npm ERR! path /Users/salman/Developer/ReactNative
npm ERR! command failed
npm ERR! command sh -c create-tamagui

npm ERR! A complete log of this run can be found in: /Users/salman/.npm/_logs/2023-07-23T17_48_43_806Z-debug-0.log
```

Uploading the log too.

[2023-07-23T17_48_43_806Z-debug-0.log](https://github.com/tamagui/tamagui/files/12139601/2023-07-23T17_48_43_806Z-debug-0.log)
