### ISSUE TITLE
Error in Select example

### ISSUE THREAD

**Issue by mattmarcello** [tamagui/tamagui#207]
**Describe the bug**

I get the following error when implementing `<Select/>` the example in my react-native@0.68.2 project.

```
[A Proxy's 'target' should be an Object]
at node_modules/@tamagui/core/dist/cjs/hooks/useMedia.js:134:10 in <anonymous>
at node_modules/@tamagui/select/dist/cjs/useSelectBreakpointActive.js:27:16 in useSelectBreakpointActive
at node_modules/@tamagui/select/dist/cjs/Select.js:374:20 in <anonymous>
```

**To Reproduce**

Copy / paste this example into a react-native project.

```
import { Check, ChevronDown, ChevronUp } from '@tamagui/feather-icons'
import React, { useState } from 'react'
import { LinearGradient, Select, YStack } from 'tamagui'

export function SelectDemo() {
  const [val, setVal] = useState('apple')
  return (
    <Select id="food" sheetBreakpoint="sm" value={val} onValueChange={setVal}>
      <Select.Trigger w={240} iconAfter={ChevronDown}>
        <Select.Value placeholder="Something" />
      </Select.Trigger>

      <Select.Sheet modal dismissOnSnapToBottom>
        <Select.Sheet.Frame>
          <Select.Sheet.ScrollView>
            <Select.SheetContents />
          </Select.Sheet.ScrollView>
        </Select.Sheet.Frame>
        <Select.Sheet.Overlay />
      </Select.Sheet>

      <Select.Content>
        <Select.ScrollUpButton ai="center" jc="center" pos="relative" w="100%" h="$3">
          <YStack zi={10}>
            <ChevronUp size={20} />
          </YStack>
          <LinearGradient
            start={[0, 0]}
            end={[0, 1]}
            fullscreen
            colors={['$background', '$backgroundTransparent']}
            br="$4"
          />
        </Select.ScrollUpButton>

        <Select.Viewport minWidth={200}>
          <Select.Group>
            <Select.Label>Fruits</Select.Label>
            {items.map((item, i) => {
              return (
                <Select.Item index={i} key={item.name} value={item.name.toLowerCase()}>
                  <Select.ItemText>{item.name}</Select.ItemText>
                  <Select.ItemIndicator ml="auto">
                    <Check size={16} />
                  </Select.ItemIndicator>
                </Select.Item>
              )
            })}
          </Select.Group>
        </Select.Viewport>

        <Select.ScrollDownButton ai="center" jc="center" pos="relative" w="100%" h="$3">
          <YStack zi={10}>
            <ChevronDown size={20} />
          </YStack>
          <LinearGradient
            start={[0, 0]}
            end={[0, 1]}
            fullscreen
            colors={['$backgroundTransparent', '$background']}
            br="$4"
          />
        </Select.ScrollDownButton>
      </Select.Content>
    </Select>
  )
}

const items = [
  { name: 'Apple' },
  { name: 'Pear' },
  { name: 'Blackberry' },
  { name: 'Peach' },
  { name: 'Apricot' },
  { name: 'Melon' },
  { name: 'Honeydew' },
  { name: 'Starfruit' },
  { name: 'Blueberry' },
  { name: 'Rasberry' },
  { name: 'Strawberry' },
  { name: 'Mango' },
  { name: 'Pineapple' },
  { name: 'Lime' },
  { name: 'Lemon' },
  { name: 'Coconut' },
  { name: 'Guava' },
  { name: 'Papaya' },
  { name: 'Orange' },
  { name: 'Grape' },
  { name: 'Jackfruit' },
  { name: 'Durian' },
]

```
**System Info (please complete the following information):** 

 System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 56.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.5

**Comment by natew** [comment]
This should be fixed, please re-open if not.
