### ISSUE TITLE
Tamagui Webpack Loader Error:    createCSSVariable expected string, got: undefined

### ISSUE THREAD

**Issue by asp2131** [tamagui/tamagui#2331]
### Current Behavior

When I run `yarn run web`, I get this error title: `Tamagui Webpack Loader Error:
   createCSSVariable expected string, got: undefined` 
   
   The rest of the error log:
```
   Error: createCSSVariable expected string, got: undefined
    at createCSSVariable (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/node_modules/@tamagui/core/node_modules/@tamagui/web/dist/cjs/createVariable.js:67:11)
    at variableToCSS (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/node_modules/@tamagui/core/node_modules/@tamagui/web/dist/cjs/helpers/registerCSSVariable.js:25:91)
    at /Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/node_modules/@tamagui/core/node_modules/@tamagui/web/dist/cjs/createTamagui.js:68:162
    at createTamagui (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/node_modules/@tamagui/core/node_modules/@tamagui/web/dist/cjs/createTamagui.js:108:5)
    at loadTamagui (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:51:107)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:71:60)
    at async Object.parse (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:88:28)
    at async extractToClassNames (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:64:15)
    at async Object.loader (/Users/akinpound/Documents/experiments/cleaningboss/node_modules/tamagui-loader/dist/cjs/loader.js:53:73)

Missing theme, an error occurred when importing your config
Got config: [Function (anonymous)] {
  displayName: 'ProxyWorm - Check excludeReactNativeWebExports',
  _isProxyWorm: true
}
Looking for theme: displayName
```

### Expected Behavior

Supposed to display the nextjs web version with  of my app

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
run `yarn web`
```

### System Info

```markdown
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 115.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.asdf/installs/nodejs/21.6.2/bin/node
    Yarn: 1.22.21 - ~/.asdf/installs/nodejs/21.6.2/bin/yarn
    npm: 8.19.4 - ~/Documents/experiments/cleaningboss/node_modules/.bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 122.1.63.161
    Chrome: 122.0.6261.69
    Safari: 15.4
  npmPackages:
    @babel/runtime: ^7.23.2 => 7.23.9 
    @manypkg/cli: ^0.19.2 => 0.19.2 
    @radix-ui/react-dropdown-menu: ^2.0.6 => 2.0.6 
    @radix-ui/react-select: ^2.0.0 => 2.0.0 
    @react-email/components: ^0.0.14 => 0.0.14 
    @react-email/render: ^0.0.12 => 0.0.12 
    @sendgrid/mail: ^8.1.0 => 8.1.1 
    @stripe/react-stripe-js: ^2.4.0 => 2.5.0 
    @stripe/stripe-js: ^2.3.0 => 2.4.0 
    @tanstack/react-query: ^5.17.19 => 5.22.2 
    check-dependency-version-consistency: ^3.3.0 => 3.3.0 
    classnames: ^2.5.1 => 2.5.1 
    eslint: ^8.53.0 => 8.57.0 
    node-gyp: ^9.4.1 => 9.4.1 
    prettier: ^3.0.3 => 3.2.5 
    react-email: ^2.0.0 => 2.1.0 
    resend: ^3.1.0 => 3.2.0 
    stripe: ^14.11.0 => 14.18.0 
    turbo: ^1.10.16 => 1.12.4 
    typescript: ^4.9.5 => 4.9.5 
    zod: ^3.22.4 => 3.22.4
```

**Comment by smontlouis** [comment]
Do you guys found any solution ? Getting the same error
