### ISSUE TITLE
Starter expo-router not working

### ISSUE THREAD

**Issue by Niible** [tamagui/tamagui#2409]
### Current Behavior

When running the starter expo-router it didn't run correctly when building for the web.

this is the output of `yarn run start` : 

```
Web Bundling failed 8979ms (node_modules/expo-router/entry.js)
Web node_modules/expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 94.6% (1097/1128)
λ node_modules/expo-router/node/render.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.0% (1341/1348)Error: ENOENT: no such file or directory, open '/home/nible/tamagui/starters/expo-router/node_modules/@expo/server/src/index.ts'
    at Object.readFileSync (node:fs:453:20)
    at getCodeFrame (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:927:18)
    at Server._symbolicate (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:1010:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:422:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/nible/tamagui/starters/expo-router/node_modules/@expo/server/src/index.ts'
}
Error: ENOENT: no such file or directory, open '/home/nible/tamagui/starters/expo-router/node_modules/@expo/server/src/vendor/http.ts'
    at Object.readFileSync (node:fs:453:20)
    at getCodeFrame (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:927:18)
    at Server._symbolicate (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:1010:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/home/nible/tamagui/starters/expo-router/node_modules/metro/src/Server.js:422:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/nible/tamagui/starters/expo-router/node_modules/@expo/server/src/vendor/http.ts'
}

Metro error: Unable to resolve module /home/nible/Wikodit/gup/gup-api/apps/front-expo/.tamagui/css/apptabslayouttsx.css from /home/nible/tamagui/starters/expo-router/app/(tabs)/_layout.tsx: 

None of these files exist:
  * ../../../Wikodit/gup/gup-api/apps/front-expo/.tamagui/css/apptabslayouttsx.css(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.css|.css)
  * ../../../Wikodit/gup/gup-api/apps/front-expo/.tamagui/css/apptabslayouttsx.css/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.css|.css)
  26 |       <Tabs.Screen
  27 |         name="two"
> 28 |         options={{
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  29 |           title: 'Tab Two',
  30 |           tabBarIcon: ({ color }) => <Text>Hello!</Text>,
  31 |         }}


Call Stack
  MetroBundlerDevServer.getStaticResourcesAsync (node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:293:13)
  processTicksAndRejections (node:internal/process/task_queues)
  MetroBundlerDevServer.getStaticPageAsync (node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:349:52)
  getHtml (node_modules/@expo/cli/src/start/server/metro/createServerRouteMiddleware.ts:78:31)
  handler (node_modules/@expo/server/src/index.ts:149:26)
Unable to resolve "/home/nible/Wikodit/gup/gup-api/apps/front-expo/.tamagui/css/apptabslayouttsx.css" from "app/(tabs)/_layout.tsx"
λ Bundling failed 8978ms (node_modules/expo-router/node/render.js)
```

### Tamagui Version

```markdown
v1.91.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
`npm create tamagui@latest` -> choose the expo-router
`cd folder`
`yarn run start` -> `w` for web
```

### System Info

```markdown
System:
    OS: Linux 5.17 Manjaro Linux
    CPU: (16) x64 Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz
    Memory: 21.41 GB / 31.07 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 4.0.2 - ~/.local/share/pnpm/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.8.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Brave Browser: 120.1.61.101
  npmPackages:
    @babel/core: ^7.23.3 => 7.23.7 
    @expo/metro-runtime: ~3.1.3 => 3.1.3 
    @react-navigation/native: ^6.0.2 => 6.1.9 
    @tamagui/config: ^1.91.3 => 1.91.3 
    @tamagui/metro-plugin: ^1.91.3 => 1.91.3 
    @types/react: ~18.2.14 => 18.2.47 
    babel-preset-expo: ^10.0.1 => 10.0.1 
    expo: ~50.0.6 => 50.0.6 
    expo-font: ~11.10.2 => 11.10.2 
    expo-linking: ~6.2.1 => 6.2.2 
    expo-router: ~3.4.7 => 3.4.7 
    expo-splash-screen: ~0.26.4 => 0.26.4 
    expo-status-bar: ~1.11.1 => 1.11.1 
    expo-system-ui: ~2.9.3 => 2.9.3 
    expo-web-browser: ~12.8.2 => 12.8.2 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-helmet-async: ~2.0.4 => 2.0.4 
    react-native: 0.73.4 => 0.73.4 
    react-native-reanimated: ~3.6.2 => 3.6.2 
    react-native-safe-area-context: 4.8.2 => 4.8.2 
    react-native-screens: ~3.29.0 => 3.29.0 
    react-native-web: ^0.19.9 => 0.19.10 
    tamagui: ^1.91.3 => 1.91.3 
    typescript: ^5.3.3 => 5.3.3
```

**Comment by BubbleTrouble14** [comment]
What was the fix ? I get this problem when just trying to run the mobile version ?
