### ISSUE TITLE
Remix starter not working in dev

### ISSUE THREAD

**Issue by ericvicenti** [tamagui/tamagui#2728]
### Current Behavior

Trying to run `yarn dev` on the Remix starter with no changes on top

```
TypeError: Cannot read properties of undefined (reading 'themes')
```

The production build works fine

### Expected Behavior

Expected to see the web page load

### Tamagui Version

```markdown
`npm create tamagui@latest` -> remix starter
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

`npm create tamagui@latest`
choose remix starter
cd into folder
`yarn dev`
open in browser

```
TypeError: Cannot read properties of undefined (reading 'themes')
    at Module.getThemes (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/config.mjs:37:26)
    at getState (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/helpers/ThemeManager.mjs:62:18)
    at ThemeManager.getState (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/helpers/ThemeManager.mjs:44:12)
    at ThemeManager.getStateIfChanged (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/helpers/ThemeManager.mjs:36:20)
    at ThemeManager.updateStateFromProps (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/helpers/ThemeManager.mjs:27:28)
    at new ThemeManager (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/helpers/ThemeManager.mjs:15:12)
    at getNewThemeManager (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/hooks/useTheme.mjs:171:42)
    at createState (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/hooks/useTheme.mjs:178:32)
    at useReducer (/Users/ericvicenti/Code/ttest2/node_modules/react-dom/cjs/react-dom-server.node.development.js:5145:57)
    at Object.useState (/Users/ericvicenti/Code/ttest2/node_modules/react-dom/cjs/react-dom-server.node.development.js:5083:10)
    at Proxy.useState (/Users/ericvicenti/Code/ttest2/node_modules/react/cjs/react.development.js:1622:21)
    at Module.useChangeThemeEffect (/Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/hooks/useTheme.mjs:104:41)
    at /Users/ericvicenti/Code/ttest2/node_modules/@tamagui/web/dist/esm/views/Theme.mjs:14:18
    at renderWithHooks (/Users/ericvicenti/Code/ttest2/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
...
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 692.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.0/bin/npm
    pnpm: 7.27.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.1 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 98.1.35.104
    Chrome: 126.0.6478.61
    Edge: 120.0.2210.144
    Safari: 17.5
  npmPackages:
    @biomejs/biome: ^1.5.3 => 1.8.1 
    @remix-run/dev: ^2.8.1 => 2.9.2 
    @remix-run/node: ^2.8.1 => 2.9.2 
    @remix-run/react: ^2.8.1 => 2.9.2 
    @remix-run/serve: ^2.8.1 => 2.9.2 
    @tamagui/config: ^1.100.5 => 1.100.5 
    @tamagui/vite-plugin: ^1.100.5 => 1.100.5 
    @types/react: ^18.2.55 => 18.3.3 
    @types/react-dom: ^18.2.19 => 18.3.0 
    isbot: ^4.1.0 => 4.4.0 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    tamagui: ^1.100.5 => 1.100.5 
    typescript: ^5.3.3 => 5.4.5 
    vite: 6.0.0-alpha.17 => 6.0.0-alpha.17 
    vite-bundle-analyzer: ^0.9.2 => 0.9.4 
    vite-plugin-commonjs: ^0.10.1 => 0.10.1 
    vite-tsconfig-paths: ^4.3.2 => 4.3.2
```

**Comment by ericvicenti** [comment]
After trying again today I get a totally different error (same reproduction step)

<img width="1023" alt="Screenshot 2024-06-26 at 9 49 52 AM" src="https://github.com/tamagui/tamagui/assets/1483597/6caebfa2-c035-4cc3-82f2-3f68d26ba367">

**Comment by ppold** [comment]
did you get it working in the end?

**Comment by natew** [comment]
@JustinINevill seems like we need to add the vite plugin for compat with react-native, i will revisit this as i've done this a few times now with other stacks.

**Comment by natew** [comment]
I simplified down to just using core in the starter for now. 3595f076a3a4e752e375cd6e8dc1d31f32ec4653

We have a vite-based stack coming soon that will solve all these issues and more!
