### ISSUE TITLE
cannot render icon in react-native-web

### ISSUE THREAD

**Issue by hcwiley** [tamagui/tamagui#2785]
### Current Behavior

When including an icon from `@tamagui/lucide-icons` I get the following error:

```
Uncaught Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering. Also, make sure all of your tamagui dependencies are on the same version (`tamagui`, `@tamagui/package-name`, etc.) not just in your package.json, but in your lockfile.
```

Complete stack trace here: 
```
config.mjs:11 Uncaught Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering. Also, make sure all of your tamagui dependencies are on the same version (`tamagui`, `@tamagui/package-name`, etc.) not just in your package.json, but in your lockfile.
    at getConfig (config.mjs:11:1)
    at usePropsAndStyle (useProps.mjs:34:75)
    at themed.mjs:11:51
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js:19425:1)
    at updateMemoComponent (react-dom.development.js:19284:1)
    at beginWork (react-dom.development.js:21673:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
getConfig @ config.mjs:11
usePropsAndStyle @ useProps.mjs:34
(anonymous) @ themed.mjs:11
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
updateSimpleMemoComponent @ react-dom.development.js:19425
updateMemoComponent @ react-dom.development.js:19284
beginWork @ react-dom.development.js:21673
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 20 more frames
Show lessUnderstand this error
react-dom.development.js:18687 The above error occurred in one of your React components:

    at http://localhost:4201/vendor.js:100944:64
    at button
    at Provider (http://localhost:4201/vendor.js:23483:5)
    at http://localhost:4201/vendor.js:22006:55
    at http://localhost:4201/vendor.js:7553:36
    at span
    at http://localhost:4201/vendor.js:27477:55
    at http://localhost:4201/vendor.js:25979:13
    at div
    at http://localhost:4201/vendor.js:22006:55
    at span
    at span
    at http://localhost:4201/vendor.js:27477:55
    at PortalProviderComponent (http://localhost:4201/vendor.js:12922:3)
    at span
    at span
    at http://localhost:4201/vendor.js:27477:55
    at ThemeProvider (http://localhost:4201/vendor.js:27673:11)
    at Provider (http://localhost:4201/vendor.js:23483:5)
    at TamaguiProvider (http://localhost:4201/vendor.js:27335:3)
    at TamaguiProvider (http://localhost:4201/vendor.js:91149:28)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show lessUnderstand this error
config.mjs:11 Uncaught Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering. Also, make sure all of your tamagui dependencies are on the same version (`tamagui`, `@tamagui/package-name`, etc.) not just in your package.json, but in your lockfile.
    at getConfig (config.mjs:11:1)
    at usePropsAndStyle (useProps.mjs:34:75)
    at themed.mjs:11:51
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js:19425:1)
    at updateMemoComponent (react-dom.development.js:19284:1)
    at beginWork (react-dom.development.js:21673:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
getConfig @ config.mjs:11
usePropsAndStyle @ useProps.mjs:34
(anonymous) @ themed.mjs:11
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
updateSimpleMemoComponent @ react-dom.development.js:19425
updateMemoComponent @ react-dom.development.js:19284
beginWork @ react-dom.development.js:21673
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 17 more frames
Show lessUnderstand this error
```

### Expected Behavior

`@tamagui/lucide-icons` should display icons. There's an issue with getting the config correctly. It appears to only be an issue on react-native-web and icons.

### Tamagui Version

```markdown
1.102.1
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://github.com/hcwiley/tamaguiNxSandbox
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (14) arm64 Apple M3 Max
    Memory: 111.63 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /opt/node/node-v20.14.0-darwin-arm64/bin/yarn
    npm: 10.8.1 - /usr/local/bin/npm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

**Comment by hcwiley** [comment]
my current hunch is that it's the fact that Icons are `memo`d so they aren't getting the updated config since the config isn't included as a dependency of the memo

**Comment by hcwiley** [comment]
did some ugly hacking. 

Tried doing the commonjs `require` directly:
```
const Icon = require('@tamagui/lucide-icons/dist/cjs/icons/plus').Plus;
```

this does NOT work:
```
const Plus = (0, import_react.memo)((0, import_helpers_icon.themed)(Icon));
```

this also does NOT work:
```
const Plus = ((0, import_helpers_icon.themed)(Icon));
```

this does!!
```
const Plus = (0, import_react.memo)((Icon));
```

So not sure what's going on with the `themed` call not being able to have context that it has the config already set.

**Comment by hcwiley** [comment]
figured out the problem by putting console.log in. 

```
import * as Icons from '@tamagui/lucide-icons'
```

on calls into the `mjs` dist while the rest of the code was using `cjs`

I changed to 

```
import * as Icons from '@tamagui/lucide-icons/dist/cjs/index.js'
```

and it's all fine now with the out the patching of the files.

**Comment by hcwiley** [comment]
removing all the `esm` dist files made this have to work

```
rm -rf $(find node_modules/@tamagui -name "esm" -type d)
```

so i'm not sure what's going with the setup on react-native-web that only lucide-icons in using the esm modules.

**Comment by natew** [comment]
This must be something to do with mis-matched deps or something, but I don't think an issue for Tamagui.

**Comment by greeenboi** [comment]
What is the fix? I am getting this on my android build on expo go.
Is is because its not added to my tamagui.config.ts?

**Comment by mattThousand** [comment]
encountering the same issue here, adjusting the import to be 
```
import * as Icons from '@tamagui/lucide-icons';
```
does not do the trick 🤔

**Comment by jonsherrard** [comment]
Triple check that all your `@tamagui/[name]` and `tamagui` packages have the same version number, re-run yarn, then restart your dev server.

**Comment by Tymek** [comment]
I had this issue. After replacing `@tamagui/lucide-icons` with `lucide-react-native` and it seems to work.

**Comment by DanielChomat** [comment]
Might not be related to your cases, but had the same error in React Native, and the problem were mis-matching versions of the `tamagui` packages.

Installed `lucide-icons` via the docs and got a newer version, than the ones installed (`1.110.2` vs. `1.110.1`).

After version-matching all of the packages, got the icons rendered on both React Native as well as the web.

**Comment by kavyantic** [comment]
I am facing the same error despite making sure that all `tamagui/[package]` and `tamagui` has the same version in package.json but some peer dependencies have mismatched version in package-lock.json. I am not sure how to align same version for peer dependencies in lock file. I am also facing this issue only when importing and using `tamagui/lucide-icons`.

**Comment by natew** [comment]
@kavyantic can you try running `npx @tamagui/cli check` it may help. If it's mistmatched in the lockfile you probably need to generate a new lockfile, if you delete and re-install it probably will align so long as your package.json is matched.

**Comment by jedokim** [comment]
> @kavyantic can you try running `npx @tamagui/cli check` it may help. If it's mistmatched in the lockfile you probably need to generate a new lockfile, if you delete and re-install it probably will align so long as your package.json is matched.

For anyone that visits this post in the future, this is what worked for me

delete yarn file and re-run
yarn add react-native-svg @tamagui/lucide-icons
