### ISSUE TITLE
`npm create tamagui@latest` throws error

### ISSUE THREAD

**Issue by guillempuche** [tamagui/tamagui#3003]
### Current Behavior

```sh
✔ Pick a template: › Remix - Remix + Vite starter with Tamagui set up


Creating a new tamagui app /Users/guillem/programacio/codi/testing/test-tamagui-tokens...
test-tamagui-tokens folder created.

Setting up /Users/guillem/.tamagui-repo-cache/tamagui/tamagui.git...
$ cd /Users/guillem/.tamagui-repo-cache
[tamagui] Failed to copy example into /Users/guillem/programacio/codi/testing/test-tamagui-tokens

 Error: Command failed: git sparse-checkout set code
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at exec (/Users/guillem/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/dist/index.cjs:31168:95)
    at setupTamaguiDotDir (/Users/guillem/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/dist/index.cjs:31213:5)
    at async cloneStarter (/Users/guillem/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/dist/index.cjs:31172:123)
    at async run (/Users/guillem/.npm/_npx/d01fabec74a282ea/node_modules/create-tamagui/dist/index.cjs:31659:7) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 67244,
  stdout: null,
  stderr: null
}
npm error code 1
npm error path /Users/guillem/programacio/codi/testing
npm error command failed
npm error command sh -c create-tamagui
npm error A complete log of this run can be found in: /Users/guillem/.npm/_logs/2024-10-18T15_30_47_532Z-debug-0.log
```

### Tamagui Version

```markdown
1.115.5
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
1. `npm create tamagui@latest`
2. Any name
3. Select Remix
```

### System Info

```markdown
Macos
```

**Comment by natew** [comment]
@jonsherrard worth a quick check just to make sure its not borked

**Comment by jonsherrard** [comment]
Hmm I used on Friday, yep working for me too now.

@guillempuche 

could run `ls -lash ~`

Then past the first line of the output - for the `.` directory.

mine looks like this for reference:

```sh
0 drwxr-x---+  112 jonsherrard  staff   3.5K Oct 21 13:29 .
```

**Comment by guillempuche** [comment]
`0 drwxr-x---+ 131 guillem  staff   4.1K Oct 21 18:50 .`

I saw that when using the starter:

```sh
Creating a new tamagui app /Users/.../test-tamagui-starter...
test-tamagui-starter folder created.

Setting up /Users/guillem/.tamagui-repo-cache/tamagui/tamagui.git...
$ cd /Users/guillem/.tamagui-repo-cache
[tamagui] Failed to copy example into /Users/.../test-tamagui-starter

 Error: Command failed: git sparse-checkout set code
 ```

**Comment by jonsherrard** [comment]
what's your git version? `git -v` out of interest?

**Comment by guillempuche** [comment]
2.46.2

**Comment by natew** [comment]
`1.116.1` going out here in a minute, i did two things: added the error stack to the output, and made the retry attempt not use sparse-checkout in case that was causing the issue. let me know if that doesn't fix it and we can re-open.
