### ISSUE TITLE
TypeError in SheetScrollView

### ISSUE THREAD

**Issue by jsve** [tamagui/tamagui#3035]
When using a modal that adapts to a sheet on 'sm', and the sheet contains a `Dialog.Sheet.ScrollView`, the console overflows with this TypeError:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'y')
    at Object.onScroll (SheetScrollView.mjs:58:24)
    at ScrollView.scrollResponderHandleScroll (index.js:92:41)
    at ScrollView._handleScroll (index.js:264:12)
    at handleScrollTick (ScrollViewBase.js:120:7)
    at handleScroll (ScrollViewBase.js:105:11)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26174:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchContinuousEvent (react-dom.development.js:6444:5)
```

the stack trace lead me to this line:

https://github.com/tamagui/tamagui/blob/fe9a4e8317fe826ada4445157be5a44164d89505/code/ui/sheet/src/SheetScrollView.tsx#L85

I can't see anything immediately wrong with that line though.

I'm on:
 - "tamagui": "1.116.9",
 - "@tamagui/next-plugin": "1.116.9",
 - "react": "18.3.1",

**Comment by natew** [comment]
What platform? Is there a way to reproduce it easily in one of the starters?

**Comment by natew** [comment]
Also the newer Tamagui does loosen react-dom as well, which *maybe* helps, but I doubt it.

**Comment by jsve** [comment]
Not sure what you mean with starters. Do you have a codesandbox or similar?

**Comment by skyriverbend** [comment]
I just came across this bug too. @natew here's a reproduction for you:

https://github.com/skyriverbend/tamagui-sheet-scroll-bug

More specifically
https://github.com/skyriverbend/tamagui-sheet-scroll-bug/blob/main/packages/app/features/home/screen.tsx

**Comment by skyriverbend** [comment]
It seems like this only produces an error on web, not native. And for web it seems fine to just use `ScrollView` instead of `Sheet.ScrollView`, so maybe we can have `Sheet.ScrollView` behave just like `ScrollView` on web?

**Comment by skyriverbend** [comment]
As a side note: scrolling in ScrollViews on Sheets on web has pretty bad UX. Scrolling up makes the sheet start to pull down even when you're not at the top of the ScrollView.

**Comment by jsve** [comment]
Just tried this on v.1.125.6 and the issue still persists there. It seems that the upgrade to 1.125.6 (from 1.116.12) prevents scrolling in the normal Dialog on touch devices, hence why I tried it.

**Comment by skyriverbend** [comment]
FYI - the workaround here for now is to not use adapt. Create a separate dialog and sheet that only display at the correct screen sizes. Then you can create a shared content component that you use in both.

**Comment by natew** [comment]
@skyriverbend actually it specifically has logic to avoid that behavior but I’ve noticed in some cases it can do it. 

This is a fully open source project I give away for free that takes tremendous effort, it’d be great if people didn’t complain about bad UX on the free product they’re being given with free support. 

Instead maybe offer to sponsor development.

**Comment by nnphong1904** [comment]
Hi @skyriverbend 

> I just came across this bug too. [@natew](https://github.com/natew) here's a reproduction for you:
> 
> https://github.com/skyriverbend/tamagui-sheet-scroll-bug
> 
> More specifically https://github.com/skyriverbend/tamagui-sheet-scroll-bug/blob/main/packages/app/features/home/screen.tsx

You should put the `<Sheet.ScrollView>` directly inside the `<Sheet>` component. Instead of putting it inside the `Dialog`

<img width="880" alt="Image" src="https://github.com/user-attachments/assets/7fec21c0-bd65-4695-abbf-b63671c34cd1" />
