### ISSUE TITLE
remix starter fails with: `Error: @tamagui/static tried to access js-yaml, but it isn't declared in its dependencies`

### ISSUE THREAD

**Issue by chris-garrett** [tamagui/tamagui#3039]
### Current Behavior

```
(py312) chris@europa:~/projects/react/apps$ npm create tamagui@latest

 Note: You may need to run "npm create tamagui@latest" to get the latest version!


▀█▀ ▄▀█ █▀▄▀█ ▄▀█ █▀▀ █ █ █
 █  █▀█ █ ▀ █ █▀█ █▄█ █▄█ █

Creating tamagui app...
✔ Project name: … tamagui-remix2
✔ Pick a template: › Remix - Remix + Vite starter with Tamagui set up


Creating a new tamagui app /home/chris/projects/react/apps/tamagui-remix2...
tamagui-remix2 folder created.

Setting up /home/chris/.tamagui-repo-cache/tamagui/tamagui.git...
$ cd /home/chris/.tamagui-repo-cache



Copying starter from /home/chris/.tamagui-repo-cache/tamagui/tamagui.git/code/starters/remix into tamagui-remix2...

tamagui-remix2 created!

$ cd /home/chris/projects/react/apps/tamagui-remix2

Installing packages. This might take a couple of minutes.

installing with yarn
> yarn install
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ - @tamagui/remix-starter@workspace:.
➤ YN0000: └ Completed in 0s 201ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1158 packages were added to the project (+ 328.99 MiB).
➤ YN0000: └ Completed in 6s 532ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @biomejs/biome@npm:1.9.2 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.24.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.7.24 [f7968] must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.7.24 [1dffd] must be built because it never has been before or the last one failed
➤ YN0007: │ vue-demi@npm:0.14.10 [a9942] must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.17.6 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 458ms
➤ YN0000: · Done with warnings in 8s 348ms

  Done! created a new project under ./tamagui-remix2

visit your project:
  cd tamagui-remix2


  To start the Remix development server, run:
    yarn dev


        ████████████
      ██            ██
    ██            ██  ██████
  ██        ██              ██
  ██                  ████████
  ██                        ██
  ██                    ████
██                    ██
██                    ██

(py312) chris@europa:~/projects/react/apps$ cd tamagui-remix2/
(py312) chris@europa:~/projects/react/apps/tamagui-remix2$ yarn dev
Error: @tamagui/static tried to access js-yaml, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: js-yaml
Required by: @tamagui/static@virtual:e0a89adaf546cc2b25d7b75848cd912ed5eaf7dc68f1a623152e50c66fad7bf6847084570b8d18dce0749635d1b0190a69b3da2c14918b8d030c6b6ea40c0763#npm:1.116.9 (via /home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/)

Require stack:
- /home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/check-dep-versions.js
- /home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/checkDeps.js
- /home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/exports.js
- /home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/index.js
    at require$$0.Module._resolveFilename (/home/chris/projects/react/apps/tamagui-remix2/.pnp.cjs:22533:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (/home/chris/projects/react/apps/tamagui-remix2/.pnp.cjs:22424:31)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/chris/projects/react/apps/tamagui-remix2/.yarn/__virtual__/@tamagui-static-virtual-ee1312d4eb/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/check-dep-versions.js:20:63)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at require$$0.Module._extensions..js (/home/chris/projects/react/apps/tamagui-remix2/.pnp.cjs:22576:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
```

### Expected Behavior

that the unmodified app starts after creation

### Tamagui Version

```markdown
$ yarn info tamagui
└─ tamagui@npm:1.116.9
   ├─ Instances: 1
   ├─ Version: 1.116.9
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
1. `npm create tamagui@latest`
2. use any name `tamagui-remix`
3. select the `Remix` template
4. `cd tamagui-remix`
5. `yarn dev`
```

### System Info

```markdown
System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 32.18 GB / 62.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.5.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 9.8.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.36 - ~/.bun/bin/bun
```

**Comment by chris-garrett** [comment]
tried the vite webpack template and same error:

```
$ yarn web
[webpack-cli] Failed to load '/home/chris/projects/react/apps/tamagui-vite-webpack/webpack.config.js' config
[webpack-cli] Error: @tamagui/static tried to access js-yaml, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: js-yaml
Required by: @tamagui/static@virtual:dc9c35891a7d99589fe7653ae69776771dd27a38a95f4854a16181da97ff2ded1c7e94973e6819077a0d5c502e383511937dbf736adb42124a2ac509b29f9888#npm:1.116.9 (via /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/)

Require stack:
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/check-dep-versions.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/checkDeps.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/exports.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/index.js
- /home/chris/.local/share/yarn/berry/cache/tamagui-loader-npm-1.116.9-dc9c35891a-10c0.zip/node_modules/tamagui-loader/dist/cjs/loader.cjs
- /home/chris/.local/share/yarn/berry/cache/tamagui-loader-npm-1.116.9-dc9c35891a-10c0.zip/node_modules/tamagui-loader/dist/cjs/index.cjs
- /home/chris/projects/react/apps/tamagui-vite-webpack/webpack.config.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/webpack-cli-virtual-1c4bfd6b94/5/.local/share/yarn/berry/cache/webpack-cli-npm-5.1.4-7be5b53b38-10c0.zip/node_modules/webpack-cli/lib/webpack-cli.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/webpack-cli-virtual-1c4bfd6b94/5/.local/share/yarn/berry/cache/webpack-cli-npm-5.1.4-7be5b53b38-10c0.zip/node_modules/webpack-cli/lib/bootstrap.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/webpack-cli-virtual-1c4bfd6b94/5/.local/share/yarn/berry/cache/webpack-cli-npm-5.1.4-7be5b53b38-10c0.zip/node_modules/webpack-cli/bin/cli.js
- /home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/webpack-virtual-79bf09e6f8/5/.local/share/yarn/berry/cache/webpack-npm-5.91.0-5571fb1057-10c0.zip/node_modules/webpack/bin/webpack.js
    at require$$0.Module._resolveFilename (/home/chris/projects/react/apps/tamagui-vite-webpack/.pnp.cjs:17222:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (/home/chris/projects/react/apps/tamagui-vite-webpack/.pnp.cjs:17113:31)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/chris/projects/react/apps/tamagui-vite-webpack/.yarn/__virtual__/@tamagui-static-virtual-5ed5a85714/5/.local/share/yarn/berry/cache/@tamagui-static-npm-1.116.9-9b9767bf21-10c0.zip/node_modules/@tamagui/static/dist/check-dep-versions.js:20:63)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at require$$0.Module._extensions..js (/home/chris/projects/react/apps/tamagui-vite-webpack/.pnp.cjs:17265:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
```

**Comment by natew** [comment]
Fix going out now - thanks.

**Comment by chris-garrett** [comment]
@natew thanks for the quick feedback. i tested this morning and am having the same issue with 1.116.12.

**Comment by natew** [comment]
@chris-garrett Pushed a fix, it was an issue with the tsconfig formatting.

**Comment by natew** [comment]
Just re-clone a new one. or format the tsconfig.json using any json formatter.

**Comment by chris-garrett** [comment]
tested the three free starters and they all work, tyvm!
