### ISSUE TITLE
Crash on default config when using v1.118.1 and expo starter

### ISSUE THREAD

**Issue by Alaa-Ben** [tamagui/tamagui#3080]
### Current Behavior

Crash when opening app whether it is on web or mobile:
`TypeError: getCSSForPlatform is not a function`
(react-native-css-interop)

### Expected Behavior

App opens without any issues

### Tamagui Version

```markdown
1.118.1
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

```markdown
- Create a new project: 
`npm create tamagui` with the expo starter (no monorepo)

- Use the default configuration with support for web


// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config')

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  // [Web-only]: Enables CSS support in Metro.
  isCSSEnabled: true,
})

// add nice web support with optimizing compiler + CSS extraction
const { withTamagui } = require('@tamagui/metro-plugin')
module.exports = withTamagui(config, {
  components: ['tamagui'],
  config: './tamagui.config.ts',
  outputCSS: './tamagui-web.css',
})


- Start app
```

**Comment by likeSo** [comment]
Same problem here!!!!
I just created a new expo project, and followed the [Expo Guide](https://tamagui.dev/docs/guides/expo)
After i changed the `metro.config.js`，this error happens!
Call stack here:

```sh
Web Bundling failed 10ms node_modules/expo-router/entry.js (1 module)
λ Bundling failed 50ms node_modules/expo-router/node/render.js (1 module)

Metro error: getCSSForPlatform is not a function


Call Stack
  processTicksAndRejections (node:internal/process/task_queues)
Web Bundling failed 18ms node_modules/expo-router/_error.js (1 module)
error: TypeError: getCSSForPlatform is not a function
    at startCSSProcessor (/Users/xxx/Desktop/ban-yin/node_modules/react-native-css-interop/src/metro/index.ts:331:7)
    at Object.getTransformOptions (/Users/xxx/Desktop/ban-yin/node_modules/react-native-css-interop/src/metro/index.ts:154:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at calcTransformerOptions (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/lib/transformHelpers.js:70:25)
    at Object.getTransformFn (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/lib/transformHelpers.js:104:51)
    at IncrementalBundler.buildGraphForEntries (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/IncrementalBundler.js:60:18)
    at IncrementalBundler.buildGraph (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/IncrementalBundler.js:134:19)
    at /Users/xxx/Desktop/ban-yin/node_modules/metro/src/IncrementalBundler.js:172:34
    at IncrementalBundler.initializeGraph (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/IncrementalBundler.js:189:24)
    at build (/Users/xxx/Desktop/ban-yin/node_modules/metro/src/Server.js:694:35)

```

**Comment by hmbrg** [comment]
Same here!

**Comment by hmbrg** [comment]
Setting `disableCSSInterop: true` in your metro.config.js seems to fix it!

**Comment by natew** [comment]
Disabling this by default as its been nothing but pain, I think this may make Expo web support require turning it not, but it's a better default. Going out in 1.119

**Comment by hmbrg** [comment]
What are the downsides of having this disabled?

**Comment by natew** [comment]
Expo Router Web mode may be breaking? Since we don't officially support it yet I felt it's fine for now to potentially break it (honestly it should just work anyway, there's nothing specifically there that should break it), but we should test the starter and see if we need to fix anything.

**Comment by hmbrg** [comment]
Web support seems to be working for me with this configured.
