### ISSUE TITLE
Latest Version (1.120.0) color scheme (light | dark) or color theme changes extremely slow

### ISSUE THREAD

**Issue by mvolonnino** [tamagui/tamagui#3094]
### Discussed in https://github.com/tamagui/tamagui/discussions/3086

<div type='discussions-op-text'>

<sup>Originally posted by **mvolonnino** December  8, 2024</sup>
Hey everyone, just getting a pulse to see if anyone else is running into the same issue I am.

I was running version `1.110.1 `before upgrading to `1.120.0` as I literally can't run version `1.110.1` anymore as metro fails to start

```
Starting project at /Users/mattvolonnino/Desktop/in-the-crease-tech-platform/in-the-crease-client
TypeError: Cannot read properties of undefined (reading 'S')
TypeError: Cannot read properties of undefined (reading 'S')
    at /Users/mattvolonnino/Desktop/in-the-crease-tech-platform/in-the-crease-client/node_modules/@tamagui/static/node_modules/react-dom/cjs/react-dom-client.development.js:22644:58
    at Object.<anonymous> (/Users/mattvolonnino/Desktop/in-the-crease-tech-platform/in-the-crease-client/node_modules/@tamagui/static/node_modules/react-dom/cjs/react-dom-client.development.js:24716:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/mattvolonnino/Desktop/in-the-crease-tech-platform/in-the-crease-client/node_modules/@tamagui/static/node_modules/react-dom/client.js:37:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

So I upgraded to the latest and now the theme changes extremely slow - upwards of 5-10 seconds. Note in the video, you can see the outline of `green` happen when I first press it & it takes 10 seconds to change the color for the app.

https://github.com/user-attachments/assets/20cb20c6-102e-454e-a8b1-b9ffdc13aa06

I utilize zustand for persisting my color mode (light or dark) & color theme (red, blue, gray, etc)

```ts
/**
 * ThemeStore
 * - persists the theme across app launches
 *
 * @important - if needing to get the *resolved* `colorMode` ('light' | 'dark') from the store, use `useTheming` hook instead
 */
const useThemeStore = createWithEqualityFn<ThemeStore>()(
  persist(
    set => ({
      themeName: track.variant === 'nightly' ? 'gray' : 'blue',
      colorMode: 'system',
      setThemeName: themeName => set({ themeName }),
      setColorMode: colorMode => set({ colorMode }),
    }),
    {
      name: 'theme-store',
      storage: createJSONStorage(() => AsyncStorage),
      version: 4,
    }
  ),
  shallow
);

export default useThemeStore;

/**
 * Hook that utilizes the `useColorScheme` & `useThemeStore` to return the correct app color mode & current theme name
 */
export const useTheming = () => {
  const appearance = useColorScheme();
  const { colorMode, themeName } = useThemeStore(s => ({
    colorMode: s.colorMode,
    themeName: s.themeName,
  }));
  const resolvedColorMode = colorMode === 'system' ? appearance! : colorMode;
  const isDark = resolvedColorMode === 'dark';

  return {
    colorMode: resolvedColorMode,
    isDark,
    isLight: resolvedColorMode === 'light',
    isSystem: colorMode === 'system',
    themeName,

    /** private field to get the exact color mode */
    _colorMode: colorMode,
    _navigation: {
      dark: DarkTheme,
      light: LightTheme,
      /** current navigation theme */
      current: isDark ? DarkTheme : LightTheme,
    },
  };
};
```

And then wrap my App with `TamaguiProvider`
```tsx
import { type PropsWithChildren } from 'react';
import { TamaguiProvider as TMGUIProvider, Theme as TamaguiTheme } from 'tamagui';
import { ToastProvider, ToastViewport } from '@tamagui/toast';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useTheming } from '@/theme/ThemeStore';
import tamaguiConfig from '@/theme/tamagui/tamagui.config';

export default function TamaguiProviders({ children }: PropsWithChildren) {
  const insets = useSafeAreaInsets();

  const { colorMode, themeName } = useTheming();

  return (
    <TMGUIProvider config={tamaguiConfig} defaultTheme={colorMode}>
      <TamaguiTheme name={themeName}>
        <ToastProvider swipeDirection="vertical" duration={6000}>
          {children}
          <ToastViewport
            top={insets.top + 5}
            right={insets.right}
            left={insets.left}
            multipleToasts
            flexDirection="column-reverse"
          />
        </ToastProvider>
      </TamaguiTheme>
    </TMGUIProvider>
  );
}
```

I didn't want to open this as an issue as you need to create a reproducible repo first - and wanted to see if anyone else runs into this issue.
</div>

**Comment by natew** [comment]
This should be fixed now in latest version

**Comment by natew** [comment]
@mvolonnino cheers, no problem. What would be a huge help is setting up a test case. I may need to fix our kitchen sink app a bit in the repo, but basically just a code snippet that really nicely illustrates it.

**Comment by natew** [comment]
Also if you can determine if there was a slowdown, tbh I just upgraded the Uniswap app to latest and it feels fast. We are using fastSchemeChange though, but some components aren't, and it feels pretty snappy. At least not worse.

**Comment by natew** [comment]
This should be fixed, we completely overhauled it in Jan and it's a lot faster. Should be good now.
