### ISSUE TITLE
Can't install `Reanimated` following the documentation

### ISSUE THREAD

**Issue by antakio** [tamagui/tamagui#453]
**Describe the bug**

**To Reproduce**
1. Create tamagui app and run yarn
```
npm create tamagui && cd ./newApp && yarn
```

2. Go to the project folder and yarn add

```
yarn add @tamagui/animations-react-native
```

3. Go to `packages/ui/src/animations.ts` and change `import { createAnimations } from '@tamagui/animations-react-native'` to `import { createAnimations } from '@tamagui/animations-reanimated'Ï`

**Getting the error:** 

```
✘ [ERROR] Could not resolve "react-native-reanimated"

    ../../node_modules/@tamagui/animations-reanimated/dist/cjs/createAnimations.js:34:53:
      34 │ var import_react_native_reanimated = __toESM(require("react-native-reanimated"));
         ╵                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "react-native-reanimated" as external to exclude it from the bundle, which
  will remove this error. You can also surround this "require" call with a try/catch block to handle
  this failure at run-time instead of bundle-time.

Tamagui Webpack Loader Error:
   Build failed with 1 error:
../../node_modules/@tamagui/animations-reanimated/dist/cjs/createAnimations.js:34:53: ERROR: Could not resolve "react-native-reanimated"
Error: Build failed with 1 error:
../../node_modules/@tamagui/animations-reanimated/dist/cjs/createAnimations.js:34:53: ERROR: Could not resolve "react-native-reanimated"
    at failureErrorWithLog (/Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:1377:14
    at /Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/admin/0WORK/PRS/portfolio/dotcom/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by antakio** [comment]
```
% npx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 554.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.6 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    @tamagui/animations-reanimated: ^1.0.1-rc.9 => 1.0.1-rc.9 
    eslint: ^8.21.0 => 8.28.0 
    prettier: ^2.7.1 => 2.8.0 
    turbo: ^1.4.2 => 1.6.3 
    typescript: ^4.7.4 => 4.9.3 
```

**Comment by natew** [comment]
Did you add `react-native-reanimated`?

**Comment by natew** [comment]
Noted that in the docs.
