### ISSUE TITLE
"yarn native" command throws error on  "@my/ui"

### ISSUE THREAD

**Issue by synnksou** [tamagui/tamagui#49]
Hello 👋, 

I have set up the starter template using "npx create-tamagui-app@latest". 

After launch "yarn native" and connect my ios device, i got this error

```
Tamagui error loading file:

    @my/ui

Cannot find module '/Users/antoine/Documents/projet-perso/test-tamagui/node_modules/@my/ui/dist/cjs'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '/Users/antoine/Documents/projet-perso/test-tamagui/node_modules/@my/ui/dist/cjs'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Mod.require (/Users/antoine/Documents/projet-perso/test-tamagui/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:56:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/antoine/Documents/projet-perso/test-tamagui/packages/app/tamagui.config.ts:3:45)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/antoine/Documents/projet-perso/test-tamagui/node_modules/esbuild-register/dist/node.js:2258:26)

iOS Bundling failed 6750ms
index.js: Call retries were exceeded
```

**Comment by cmaycumber** [comment]
I think this happens when you haven't built the UI package because it can't resolve the path `dist/cjs`. 

After building this was solved for me; I did run web, however.

**Comment by natew** [comment]
Oh yea you'll need to run `yarn watch` alongside your other commands. I should document this...
