### ISSUE TITLE
[bug] jest ListItem TypeError: Cannot use 'in' operator to search for 'defaultPrevented' in undefined

### ISSUE THREAD

**Issue by lightchaser411** [tamagui/tamagui#565]
```tsx
it('should render', () => {
    const it = render(
      <ListItem
        testID="list-item-input"
        bg="$background"
      >
        <Input />
      </ListItem>
    );
    const input = it.getByTestId('list-item-input');
    fireEvent.press(input, {});
  });
```

The event is undefined

stack trace:
```
TypeError: Cannot use 'in' operator to search for 'defaultPrevented' in undefined

      at Object.composedEventHandler [as onStartShouldSetResponder] (../../node_modules/@tamagui/helpers/src/composeEventHandlers.ts:16:34)
      at onStartShouldSetResponder (../../node_modules/@testing-library/react-native/src/fireEvent.ts:61:44)
      at isEventEnabled (../../node_modules/@testing-library/react-native/src/fireEvent.ts:80:18)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:87:10)
      at findEventHandler (../../node_modules/@testing-library/react-native/src/fireEvent.ts:112:19)
```
literally latest everything

here's a jest config if you need one:

```
/* eslint-disable */
export default {
  displayName: 'ui',
  preset: 'jest-expo',
  setupFiles: ['./tests/setup.ts'],
  // setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  transformIgnorePatterns: [
    //   // 'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
  ],
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': [
      'babel-jest',
      {
        presets: [
          '@nrwl/react/babel',
          'module:metro-react-native-babel-preset',
        ],
        plugins: [['@babel/plugin-proposal-private-methods', { loose: true }]],
      },
    ],
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$':
      require.resolve('jest-expo/src/preset/assetFileTransformer.js'),
  },
  // moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  collectCoverage: true,
  coverageDirectory: '../../coverage/libs/ui',
};

```

and a setup.ts

```
process.env.TAMAGUI_TARGET = 'native';
const EMPTY_INSETS = { left: 0, top: 0, bottom: 0, right: 0 };
jest.mock('react-native-safe-area-context', () => ({
  SafeAreaProvider({ children }) {
    return children;
  },
  useSafeAreaInsets() {
    return EMPTY_INSETS;
  },
}));

jest.mock('solito/router', () => ({
  useRouter() {
    return { back: jest.fn(), push: jest.fn() };
  },
}));

jest.mock('react-native/Libraries/Utilities/Platform', () => {
  let platform: any = {
    OS: 'ios',
  };

  const select = jest.fn().mockImplementation((obj) => {
    const value = obj[platform.OS];
    return !value ? obj.default : value;
  });

  platform.select = select;

  return platform;
});

// include this line for mocking react-native-gesture-handler
import 'react-native-gesture-handler/jestSetup';

// include this section and the NativeAnimatedHelper section for mocking react-native-reanimated
jest.mock('react-native-reanimated', () => {
  const Reanimated = require('react-native-reanimated/mock');

  // The mock for `call` immediately calls the callback which is incorrect
  // So we override it with a no-op
  Reanimated.default.call = () => {};

  return Reanimated;
});

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
```

patch to fix
```
diff --git a/dist/cjs/composeEventHandlers.js b/dist/cjs/composeEventHandlers.js
index 74afa37280e43eb691fbb83c6e781db361f3da58..a5afa7bfbb03f72e42e62d76945aa6834138ac97 100644
--- a/dist/cjs/composeEventHandlers.js
+++ b/dist/cjs/composeEventHandlers.js
@@ -1,4 +1,4 @@
-"use strict";
+'use strict';
 var __defProp = Object.defineProperty;
 var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
 var __getOwnPropNames = Object.getOwnPropertyNames;
@@ -8,17 +8,21 @@ var __export = (target, all) => {
     __defProp(target, name, { get: all[name], enumerable: true });
 };
 var __copyProps = (to, from, except, desc) => {
-  if (from && typeof from === "object" || typeof from === "function") {
+  if ((from && typeof from === 'object') || typeof from === 'function') {
     for (let key of __getOwnPropNames(from))
       if (!__hasOwnProp.call(to, key) && key !== except)
-        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
+        __defProp(to, key, {
+          get: () => from[key],
+          enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable,
+        });
   }
   return to;
 };
-var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
+var __toCommonJS = (mod) =>
+  __copyProps(__defProp({}, '__esModule', { value: true }), mod);
 var composeEventHandlers_exports = {};
 __export(composeEventHandlers_exports, {
-  composeEventHandlers: () => composeEventHandlers
+  composeEventHandlers: () => composeEventHandlers,
 });
 module.exports = __toCommonJS(composeEventHandlers_exports);
 function composeEventHandlers(og, next, { checkDefaultPrevented = true } = {}) {
@@ -27,13 +31,18 @@ function composeEventHandlers(og, next, { checkDefaultPrevented = true } = {}) {
   }
   return function composedEventHandler(event) {
     og == null ? void 0 : og(event);
-    if (!(checkDefaultPrevented && "defaultPrevented" in event) || "defaultPrevented" in event && !event.defaultPrevented) {
+    if (
+      !event ||
+      !(checkDefaultPrevented && 'defaultPrevented' in event) ||
+      ('defaultPrevented' in event && !event.defaultPrevented)
+    ) {
       return next == null ? void 0 : next(event);
     }
   };
 }
 // Annotate the CommonJS export names for ESM import in node:
-0 && (module.exports = {
-  composeEventHandlers
-});
+0 &&
+  (module.exports = {
+    composeEventHandlers,
+  });
 //# sourceMappingURL=composeEventHandlers.js.map
diff --git a/dist/esm/composeEventHandlers.js b/dist/esm/composeEventHandlers.js
index f635dd8aebbf869045f3f19458adedaff037d8e1..3cc7f8e0640510ac13bee7c6050afcda01b19f39 100644
--- a/dist/esm/composeEventHandlers.js
+++ b/dist/esm/composeEventHandlers.js
@@ -4,12 +4,14 @@ function composeEventHandlers(og, next, { checkDefaultPrevented = true } = {}) {
   }
   return function composedEventHandler(event) {
     og == null ? void 0 : og(event);
-    if (!(checkDefaultPrevented && "defaultPrevented" in event) || "defaultPrevented" in event && !event.defaultPrevented) {
+    if (
+      !event ||
+      !(checkDefaultPrevented && 'defaultPrevented' in event) ||
+      ('defaultPrevented' in event && !event.defaultPrevented)
+    ) {
       return next == null ? void 0 : next(event);
     }
   };
 }
-export {
-  composeEventHandlers
-};
+export { composeEventHandlers };
 //# sourceMappingURL=composeEventHandlers.js.map
diff --git a/dist/jsx/composeEventHandlers.js b/dist/jsx/composeEventHandlers.js
index b7ba425bef9b6380522e0a7f0753d1ec18df9298..e08c02841067b15392a092452642e3abb8b05005 100644
--- a/dist/jsx/composeEventHandlers.js
+++ b/dist/jsx/composeEventHandlers.js
@@ -4,12 +4,14 @@ function composeEventHandlers(og, next, { checkDefaultPrevented = true } = {}) {
   }
   return function composedEventHandler(event) {
     og?.(event);
-    if (!(checkDefaultPrevented && "defaultPrevented" in event) || "defaultPrevented" in event && !event.defaultPrevented) {
+    if (
+      !event ||
+      !(checkDefaultPrevented && 'defaultPrevented' in event) ||
+      ('defaultPrevented' in event && !event.defaultPrevented)
+    ) {
       return next?.(event);
     }
   };
 }
-export {
-  composeEventHandlers
-};
+export { composeEventHandlers };
 //# sourceMappingURL=composeEventHandlers.js.map
diff --git a/src/composeEventHandlers.ts b/src/composeEventHandlers.ts
index db8cce2223a8b6ac5a7f1f2f330e2ae32345211d..beb9e948d86e38bc87844d6d3f291a0eb3efb3c6 100644
--- a/src/composeEventHandlers.ts
+++ b/src/composeEventHandlers.ts
@@ -1,6 +1,6 @@
-type Events = Object
+type Events = Object;
 
-export type EventHandler<E extends Events> = (event: E) => void
+export type EventHandler<E extends Events> = (event: E) => void;
 
 export function composeEventHandlers<E extends Events>(
   og?: EventHandler<E>,
@@ -8,16 +8,17 @@ export function composeEventHandlers<E extends Events>(
   { checkDefaultPrevented = true } = {}
 ) {
   if (!og || !next) {
-    return next || og
+    return next || og;
   }
   return function composedEventHandler(event: E) {
-    og?.(event)
+    og?.(event);
     if (
+      !event ||
       !(checkDefaultPrevented && 'defaultPrevented' in event) ||
       // @ts-ignore
       ('defaultPrevented' in event && !event.defaultPrevented)
     ) {
-      return next?.(event)
+      return next?.(event);
     }
-  }
+  };
 }
```

**Comment by natew** [comment]
Event shouldn't be undefined there but made your change, thanks for the detailed report. Maybe better fix is somewhere else higher up.

Fixed in 4621f078c9d4aca32eb522b66008ec533b4a168e
