### ISSUE TITLE
Starter app with expo-dev-client bug

### ISSUE THREAD

**Issue by ivopr** [tamagui/tamagui#62]
**Describe the bug**
So, I've created a new tmagui app via `create-tamagui-app`, added `expo-dev-client` to the expo app dependencies and `import 'expo-dev-client'` to the top of `App.tsx`, built the dev client, ran `yarn build` at the root to build `@my/ui`, and the app welcomed me with a beautiful red logbox.
On console this is what I have.

<details>
  <summary>Logs</summary>

  ```
     Warning: forwardRef render functions accept exactly two parameters: props and ref. %s, Did you forget to use the ref parameter?
at /home/ivopr/projects/test/node_modules/react/cjs/react.development.js:220:4 in printWarning
at /home/ivopr/projects/test/node_modules/react/cjs/react.development.js:196:16 in error
at /home/ivopr/projects/test/node_modules/react/cjs/react.development.js:1377:13 in forwardRef
at /home/ivopr/projects/test/node_modules/@tamagui/card/dist/cjs/Card.js:115:78 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/@tamagui/card/dist/cjs/index.js:17:31 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/tamagui/dist/cjs/index.js:130:31 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/ui/dist/cjs/index.js:17:31 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/app/features/home/screen.tsx:7:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/app/navigation/native/index.tsx:4:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at App.tsx:3:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
at http://10.0.0.105:8081/index.bundle?platform=android&dev=true&minify=false&app=com.demonicat.tamaguitest&modulesOnly=false&runModule=true:370652:3 in global code

ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
at /home/ivopr/projects/test/node_modules/react-native/index.js:470:4 in module.exports.get__ViewPropTypes
at /home/ivopr/projects/test/node_modules/@react-native-community/blur/src/BlurView.android.js:87:6 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/@react-native-community/blur/index.js:1:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/tamagui/dist/cjs/views/BlurView.native.js:23:25 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/tamagui/dist/cjs/index.js:150:31 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/ui/dist/cjs/index.js:17:31 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/app/features/home/screen.tsx:7:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/packages/app/navigation/native/index.tsx:4:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at App.tsx:3:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at /home/ivopr/projects/test/node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
at http://10.0.0.105:8081/index.bundle?platform=android&dev=true&minify=false&app=com.demonicat.tamaguitest&modulesOnly=false&runModule=true:370652:3 in global code

Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

This error is located at:
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in Unknown (created by Provider)
    in Provider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at /home/ivopr/projects/test/node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at /home/ivopr/projects/test/node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at /home/ivopr/projects/test/node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:4 in showErrorDialog
at /home/ivopr/projects/test/node_modules/expo-font/build/FontHooks.js:26:33 in loadAsync.then$argument_0

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function, 
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
  ```
</details>

Only the warning about PropTypes is yellow (not sure if this will be of any use tho)

**To Reproduce**
Create a new tamagui app, add `expo-dev-client`, add `import 'expo-dev-client'` on top of `App.tsx`. Run `eas build:configure` to setup eas build. Build with `eas build -p android --profile development`. Start dev client `yarn native --dev-client`, try to run on the built APK.

**Environment (please complete the following information):**
 - OS: Android
 - Browser ?
 - Version 12

**Comment by ivopr** [comment]
So, after reading, rebuilding and testing so far I've found the following:
- Missing `react-native-safe-area-context` dep on expo
- Missing `react-native-svg` dep on expo
- Missing `expo.scheme` property on `app.json`

**Comment by natew** [comment]
Thanks for checking into this, I had run expo from clean install somewhat recently, wonder if those regressed. I'll try again here tonight and see if I get those same errors.

**Comment by natew** [comment]
Made those changes but setting `expo.scheme` in app.json seemed not to fix the Linking warning despite trying a few. You can see the latest start repo.

**Comment by ivopr** [comment]
I think you set it on the wrong `app.json`, also, what are the use of those `app.json` and `assets` folder on root? From my tests, expo is picking those on `expo folder`

**Comment by natew** [comment]
Great catch, just got mixed in accidentally.
