### ISSUE TITLE
[bug] Warning when adding button to page on web

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#661]
**Describe the bug**
On the latest version of tamagui adding a button shows an error in the console

**To Reproduce**

1. Create a new starter repo
2. Add a button to the home page
```jsx
        <H1 ta="center">Welcome to Tamagui.</H1>
        <Button>submit</Button>
        <Paragraph ta="center">
          Here's a basic starter to show navigating from one screen to another. This screen uses the
          same code on Next.js and React Native.
        </Paragraph>
```
4. See warning in console

```
Warning: Unknown event handler property `onPress`. It will be ignored.
    at a
    at span
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/createComponent.js:108:41)
    at Button (webpack-internal:///../../node_modules/@tamagui/button/dist/esm/Button.js:95:7)
    at span
    at Theme (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/views/Theme.js:23:13)
    at WithTheme (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/helpers/themeable.js:15:13)
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/createComponent.js:108:41)
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/createComponent.js:108:41)
    at HomeScreen (webpack-internal:///../../packages/app/features/home/screen.tsx:25:75)
    at NavigationProvider (webpack-internal:///../../packages/app/provider/navigation/index.web.tsx:12:11)
    at PortalProviderComponent (webpack-internal:///../../node_modules/@tamagui/portal/dist/esm/GorhomPortal.js:141:3)
```

**Comment by natew** [comment]
Fix is in next release.
