### ISSUE TITLE
Failures with tamagui-loader for webpack

### ISSUE THREAD

**Issue by CarlosHdez** [tamagui/tamagui#78]
**Describe the bug**
After following the installation steps and the starters demo for expo, I get an error from `tamagui-loader` when trying to run the web version

``` 
ERROR TypeError: this.getOptions is not a function
at Object.loader (/repo/packages/client/node_modules/tamagui-loader/src/loader.ts:32:47)
at LOADER_EXECUTION (/repo/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
at runSyncOrAsync (/repo/packages/client/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
at iterateNormalLoaders (/repo/packages/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
at Array.<anonymous> (/repo/packages/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
at Storage.finished (/repo/packages/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
at /repo/packages/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
at /repo/packages/client/node_modules/graceful-fs/graceful-fs.js:123:16
at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

```
// webpack.config.js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const { shouldExclude } = require('tamagui-loader');

module.exports = async function (env, argv) {
	const config = await createExpoWebpackConfigAsync(env, argv);
	// Customize the config before returning it.

	const DefinePlugin = config.plugins.find((x) => x.constructor.name === 'DefinePlugin')
	DefinePlugin.definitions['process.env']['TAMAGUI_TARGET'] = `"web"`
	const rules = config.module.rules[1].oneOf
	const ruleIndex = rules.findIndex((x) => x.use?.loader?.includes('babel-loader'))
	rules[ruleIndex] = {
		test: /\.(mjs|[jt]sx?)$/,
		use: [
			{
				loader: 'tamagui-loader',
				options: {
					config: './tamagui.config.ts',
					components: ['tamagui'],
				}
			}
		]
	}

	return config;
};
```

**To Reproduce**
With this configuration running `expo start --web`

**Environment (please complete the following information):**
 - OS: [e.g. Macos ]

**Comment by natew** [comment]
Looks like this may be a version issue, can you check and see if using `resolutions` and fixing the version helps?

https://stackoverflow.com/questions/68580273/type-error-this-getoptions-is-not-a-function-for-style-loader

**Comment by natew** [comment]
@CarlosHdez also webpack 5 should have better compat, if using webpack 4 maybe that's the issue.

**Comment by natew** [comment]
Feel free to re-open with more info
