### ISSUE TITLE
[bug] type=module in package.json breaks vite plugin.

### ISSUE THREAD

**Issue by petyosi** [tamagui/tamagui#815]
**Describe the bug**

Adding `"type": "module"` to package.json breaks the vite build with the following error:

```
failed to load config from /***/tamagui-test/vite.config.ts
error during build:
file:///***/tamagui-test/vite.config.ts.timestamp-1679330672678.mjs:5
import { tamaguiExtractPlugin, tamaguiPlugin } from "file:///***/tamagui-test/node_modules/.pnpm/@tamagui+vite-plugin@1.7.8_zaajv3gxstsemkvlx35v34uera/node_modules/@tamagui/vite-plugin/dist/esm/index.mjs";
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'file:///***/tamagui-test/node_modules/.pnpm/@tamagui+vite-plugin@1.7.8_zaajv3gxstsemkvlx35v34uera/node_modules/@tamagui/vite-plugin/dist/esm/index.mjs' does not provide an export named 'tamaguiExtractPlugin'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadConfigFromBundledFile (file:///***/tamagui-test/node_modules/.pnpm/vite@4.2.0_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:63952:21)
    at async loadConfigFromFile (file:///***/tamagui-test/node_modules/.pnpm/vite@4.2.0_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:63837:28)
    at async resolveConfig (file:///***/tamagui-test/node_modules/.pnpm/vite@4.2.0_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:63451:28)
    at async build (file:///***/tamagui-test/node_modules/.pnpm/vite@4.2.0_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-c167897e.js:46073:20)
    at async CAC.<anonymous> (file:///***/tamagui-test/node_modules/.pnpm/vite@4.2.0_@types+node@18.15.3/node_modules/vite/dist/node/cli.js:813:9)
 ELIFECYCLE  Command failed with exit code 1.
```

It's seems to be broken with both Node 16 and 18. 

**To Reproduce**

Clone [this repo](https://github.com/petyosi/tamagui-test/tree/type-module), checkout the **type-module** branch, do `pnpm install`, then run `pnpm build`. 

**System Info:** 

```
❯ pnpx envinfo --system --npmPackages --binaries --browsers
.../Library/pnpm/store/v3/tmp/dlx-82320  |   +1 +
.../Library/pnpm/store/v3/tmp/dlx-82320  | Progress: resolved 1, reused 1, downloaded 0, added 1, done

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.31 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @tamagui/core: ^1.7.8 => 1.7.8
    @tamagui/shorthands: ^1.7.8 => 1.7.8
    @tamagui/themes: ^1.7.8 => 1.7.8
    @tamagui/vite-plugin: ^1.7.8 => 1.7.8
    @tamagui/web: ^1.7.8 => 1.7.8
    @types/node: ^18.15.3 => 18.15.3
    @types/react: ^18.0.28 => 18.0.28
    @types/react-dom: ^18.0.11 => 18.0.11
    @vitejs/plugin-react: ^3.1.0 => 3.1.0
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native: ^0.71.4 => 0.71.4
    react-native-web: ^0.18.12 => 0.18.12
    tamagui: ^1.7.8 => 1.7.8
    typescript: ^4.9.3 => 4.9.5
    vite: ^4.2.0 => 4.2.0
```

**Comment by horacioh** [comment]
maybe your issue was fixed, because I did run your repo and it was working (the `main.tsx` file is missing but it was easy to recreate).

I see other issues with the plugin tho, maybe is an issue with the version I'm using for other dependencies? I will double check

**Comment by petyosi** [comment]
@horacioh thank you for getting back to me. I upgraded to the latest version, and the `build` step passes. There's no main, because the example is meant to compile a library, not an app. I've pushed the upgrade for reference. 

However, the CSS extraction does not work, unless I am missing something. there are only two files in the `dist` directory. This is however a different issue, so I am closing this one. Let me know if you need some help with this in general.
