### ISSUE TITLE
Iterator value textDecorationLine is not an entry object | bug

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#83]
When I create a variant where I use property: textDecorationLine. I see the following error during rendering: Iterator value textDecorationLine is not an entry object

```tsx
const StyledText = styled(SizableText, {
  variants: {
    underline: {
      true: {
        textDecorationLine: 'underline',
      },
      false: {
        textDecorationLine: 'none',
      },
    },
  },
  defaultVariants: {
   underline: false,
  }
});

// render
<StyledText underline />
```

Stacktrace:
Uncaught TypeError: Iterator value textDecorationLine is not an entry object
    at Function.fromEntries (<anonymous>)
    at updateReactDOMStyle (getStylesAtomic.ts:113:33)
    at expandStyles (getStylesAtomic.ts:17:5)
    at Object.mapper [as propMapper] (fixNativeShadow.tsx:75:43)
    at getSubStyle (getVariantExtras.tsx:448:35)
    at getSplitStyles (getVariantExtras.tsx:296:28)
    at useSplitStyles (getVariantExtras.tsx:428:15)
    at createVariable.ts:154:39
    at renderWithHooks (Dimensions.js:16175:18)
    at updateForwardRef (Dimensions.js:20023:20)
    at beginWork (Dimensions.js:22465:16)

 - OS:Mac
 - Browser Safari
 - Version beta 46

**Comment by natew** [comment]
Fixed in https://github.com/tamagui/tamagui/pull/87
