### ISSUE TITLE
Build error after bumping to 1.13.4

### ISSUE THREAD

**Issue by VladyslavKochetkov** [tamagui/tamagui#932]
### Current Behavior

Failed to run on NextJS on web, no errors on SSR. Using Solito configuration. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/33583906/230953041-50bce6ca-3ecc-4e4e-9091-c353a19b2cb7.png">

```
dex.js:264 Uncaught ReferenceError: _$o is not defined
    at eval (Anchor.js:1:273)
    at ../../node_modules/tamagui/dist/esm/views/Anchor.js (_app.js?ts=1681147089953:21862:1)
    at options.factory (webpack.js?ts=1681147089953:681:31)
    at __webpack_require__ (webpack.js?ts=1681147089953:37:33)
    at fn (webpack.js?ts=1681147089953:336:21)
    at eval (VM343 index.mjs:231:72)
    at ../../node_modules/tamagui/dist/esm/index.mjs (_app.js?ts=1681147089953:28298:1)
    at options.factory (webpack.js?ts=1681147089953:681:31)
    at __webpack_require__ (webpack.js?ts=1681147089953:37:33)
    at fn (webpack.js?ts=1681147089953:336:21)
    at eval (index.tsx:10:65)
    at ../../packages/app/provider/tamagui-provider/index.tsx (_app.js?ts=1681147089953:21556:1)
    at options.factory (webpack.js?ts=1681147089953:681:31)
    at __webpack_require__ (webpack.js?ts=1681147089953:37:33)
    at fn (webpack.js?ts=1681147089953:336:21)
    at eval (_app.tsx:15:88)
    at ./pages/_app.tsx (_app.js?ts=1681147089953:21402:1)
    at options.factory (webpack.js?ts=1681147089953:681:31)
    at __webpack_require__ (webpack.js?ts=1681147089953:37:33)
    at fn (webpack.js?ts=1681147089953:336:21)
    at eval (?f01e:5:16)
    at eval (route-loader.js:211:51)
```

``` js
// Anchor.js
import{jsx as g}from"react/jsx-runtime";import{isWeb as m,styled as c}from"@tamagui/core";import{SizableText as s}from"@tamagui/text";import{forwardRef as l}from"react";import{Linking as f}from"react-native";const o=c(s,{name:"Anchor",tag:"a",accessibilityRole:"link"}),p=o.extractable(l(({href:t,target:r,...e},i)=>g(o,{...e,...m?{href:t,target:r}:{onPress:a=>{var n;(n=e.onPress)==null||n.call(e,a),t!==void 0&&f.openURL(t)}},ref:i})));export{p as Anchor};
//# sourceMappingURL=Anchor.js.map
```

``` js
// Anchor.js (formatted)
import {jsx as g} from "react/jsx-runtime";
import {isWeb as m, styled as c} from "@tamagui/core";
import {SizableText as s} from "@tamagui/text";
import {forwardRef as l} from "react";
import {Linking as f} from "react-native";
const o = c(s, {
    name: "Anchor",
    tag: "a",
    accessibilityRole: "link"
})
  , p = o.extractable(l(({href: t, target: r, ...e},i)=>g(o, {
    ...e,
    ...m ? {
        href: t,
        target: r
    } : {
        onPress: a=>{
            var n;
            (n = e.onPress) == null || n.call(e, a),
            t !== void 0 && f.openURL(t)
        }
    },
    ref: i
})));
export {p as Anchor};
//# sourceMappingURL=Anchor.js.map
```

``` js
// Anchor.js source mapped
__webpack_require__.r(__webpack_exports__);
/* harmony export */
__webpack_require__.d(__webpack_exports__, {
    /* harmony export */
    "Anchor": function() {
        return /* binding */
        p;
    }/* harmony export */
});
/* harmony import */
var _swc_helpers_src_object_spread_mjs__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! @swc/helpers/src/_object_spread.mjs */
"../../node_modules/next/node_modules/@swc/helpers/src/_object_spread.mjs");
/* harmony import */
var _swc_helpers_src_object_spread_props_mjs__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! @swc/helpers/src/_object_spread_props.mjs */
"../../node_modules/next/node_modules/@swc/helpers/src/_object_spread_props.mjs");
/* harmony import */
var _swc_helpers_src_object_without_properties_mjs__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! @swc/helpers/src/_object_without_properties.mjs */
"../../node_modules/next/node_modules/@swc/helpers/src/_object_without_properties.mjs");
/* harmony import */
var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react/jsx-runtime */
"../../node_modules/react/jsx-runtime.js");
/* harmony import */
var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/
__webpack_require__.n(react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */
var _tamagui_core__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @tamagui/core */
"../../node_modules/@tamagui/core/dist/esm/index.mjs");
/* harmony import */
var _tamagui_text__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @tamagui/text */
"../../node_modules/@tamagui/text/dist/esm/index.mjs");
/* harmony import */
var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react */
"../../node_modules/react/index.js");
/* harmony import */
var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/
__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */
var react_native__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! react-native */
"../../node_modules/react-native-web-lite/dist/esm/index.js");

var p = _$o.extractable(/*#__PURE__*/
(0,
react__WEBPACK_IMPORTED_MODULE_1__.forwardRef)(function(_param, i) {
    var _$o = (0,
    _tamagui_core__WEBPACK_IMPORTED_MODULE_2__.styled)(_tamagui_text__WEBPACK_IMPORTED_MODULE_3__.SizableText, {
        name: "Anchor",
        tag: "a",
        accessibilityRole: "link"
    })
      , t = _param.href
      , r = _param.target
      , e = (0,
    _swc_helpers_src_object_without_properties_mjs__WEBPACK_IMPORTED_MODULE_4__["default"])(_param, ["href", "target"]);
    return (0,
    react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(_$o, (0,
    _swc_helpers_src_object_spread_props_mjs__WEBPACK_IMPORTED_MODULE_5__["default"])((0,
    _swc_helpers_src_object_spread_mjs__WEBPACK_IMPORTED_MODULE_6__["default"])({}, e, _tamagui_core__WEBPACK_IMPORTED_MODULE_2__.isWeb ? {
        href: t,
        target: r
    } : {
        onPress: function(a) {
            var n;
            (n = e.onPress) == null || n.call(e, a),
            t !== void 0 && react_native__WEBPACK_IMPORTED_MODULE_7__.Linking.openURL(t);
        }
    }), {
        ref: i
    }));
}));
//# sourceMappingURL=Anchor.js.map

;// Wrapped in an IIFE to avoid polluting the global scope
;(function() {
    var _a, _b;
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' && // AMP / No-JS mode does not inject these helpers:
    '$RefreshHelpers$'in self) {
        // @ts-ignore __webpack_module__ is global
        var currentExports = module.exports;
        // @ts-ignore __webpack_module__ is global
        var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;
        // This cannot happen in MainTemplate because the exports mismatch between
        // templating and execution.
        self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);
        // A module can be accepted automatically based on its exports, e.g. when
        // it is a Refresh Boundary.
        if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {
            // Save the previous exports on update so we can compare the boundary
            // signatures.
            module.hot.dispose(function(data) {
                data.prevExports = currentExports;
            });
            // Unconditionally accept an update to this module, we'll check if it's
            // still a Refresh Boundary later.
            // @ts-ignore importMeta is replaced in the loader
            module.hot.accept();
            // This field is set when the previous version of this module was a
            // Refresh Boundary, letting us know we need to check for invalidation or
            // enqueue an update.
            if (prevExports !== null) {
                // A boundary can become ineligible if its exports are incompatible
                // with the previous exports.
                //
                // For example, if you add/remove/change exports, we'll want to
                // re-execute the importing modules, and force those components to
                // re-render. Similarly, if you convert a class component to a
                // function, we want to invalidate the boundary.
                if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {
                    module.hot.invalidate();
                } else {
                    self.$RefreshHelpers$.scheduleUpdate();
                }
            }
        } else {
            // Since we just executed the code for the module, it's possible that the
            // new exports made it ineligible for being a boundary.
            // We only care about the case when we were _previously_ a boundary,
            // because we already accepted this update (accidental side effect).
            var isNoLongerABoundary = prevExports !== null;
            if (isNoLongerABoundary) {
                module.hot.invalidate();
            }
        }
    }
}
)();
//# sourceURL=[module]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi4vLi4vbm9kZV9tb2R1bGVzL3RhbWFndWkvZGlzdC9lc20vdmlld3MvQW5jaG9yLmpzLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7O0FBQUE7OztBQUF3QztBQUFrRDtBQUE0QztBQUFtQztBQUF1QztBQUFBLElBQThEWSxDQUFDLEdBQUNDLEdBQUMsQ0FBQ0MsV0FBVyxlQUFDTCxpREFBQyxDQUFDLGlCQUF3Qk0sQ0FBQyxFQUFHZDtRQUF0R1ksR0FBQyxHQUFDUixxREFBQyxDQUFDRSxzREFBQyxFQUFDO1FBQUNTLElBQUksRUFBQyxRQUFRO1FBQUNDLEdBQUcsRUFBQyxHQUFHO1FBQUNDLGlCQUFpQixFQUFDLE1BQU07S0FBQyxDQUFDLEVBQXFCQyxDQUFNLFVBQU5BLElBQUksRUFBR0UsQ0FBUSxVQUFSQSxNQUFNLEVBQU1FLENBQUM7UUFBcEJKLE1BQUk7UUFBR0UsUUFBTTs7V0FBYXBCLHNEQUFDLENBQUNZLEdBQUMsRUFBQyx3S0FBSVUsQ0FBQyxFQUFJcEIsZ0RBQUMsR0FBQztRQUFDZ0IsSUFBSSxFQUFDQyxDQUFDO1FBQUNDLE1BQU0sRUFBQ0MsQ0FBQztLQUFDLEdBQUM7UUFBQ0UsT0FBTyxFQUFDQyxTQUFBQSxDQUFDLEVBQUU7WUFBQyxJQUFJQyxDQUFDO1lBQUMsQ0FBQ0EsQ0FBQyxHQUFDSCxDQUFDLENBQUNDLE9BQU8sQ0FBQyxJQUFFLElBQUksSUFBRUUsQ0FBQyxDQUFDQyxJQUFJLENBQUNKLENBQUMsRUFBQ0UsQ0FBQyxDQUFDLEVBQUNMLENBQUMsS0FBRyxLQUFLLENBQUMsSUFBRVQseURBQVMsQ0FBQ1MsQ0FBQyxDQUFDO1NBQUM7S0FBQztRQUFDUyxHQUFHLEVBQUNkLENBQUM7TUFBQyxDQUFDO0NBQUEsQ0FBQyxDQUFDO0FBQXFCLENBQzFjLGtDQUFrQyIsInNvdXJjZXMiOlsid2VicGFjazovL19OX0UvLi4vLi4vbm9kZV9tb2R1bGVzL3RhbWFndWkvZGlzdC9lc20vdmlld3MvQW5jaG9yLmpzPzRkYjMiXSwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0e2pzeCBhcyBnfWZyb21cInJlYWN0L2pzeC1ydW50aW1lXCI7aW1wb3J0e2lzV2ViIGFzIG0sc3R5bGVkIGFzIGN9ZnJvbVwiQHRhbWFndWkvY29yZVwiO2ltcG9ydHtTaXphYmxlVGV4dCBhcyBzfWZyb21cIkB0YW1hZ3VpL3RleHRcIjtpbXBvcnR7Zm9yd2FyZFJlZiBhcyBsfWZyb21cInJlYWN0XCI7aW1wb3J0e0xpbmtpbmcgYXMgZn1mcm9tXCJyZWFjdC1uYXRpdmVcIjtjb25zdCBvPWMocyx7bmFtZTpcIkFuY2hvclwiLHRhZzpcImFcIixhY2Nlc3NpYmlsaXR5Um9sZTpcImxpbmtcIn0pLHA9by5leHRyYWN0YWJsZShsKCh7aHJlZjp0LHRhcmdldDpyLC4uLmV9LGkpPT5nKG8sey4uLmUsLi4ubT97aHJlZjp0LHRhcmdldDpyfTp7b25QcmVzczphPT57dmFyIG47KG49ZS5vblByZXNzKT09bnVsbHx8bi5jYWxsKGUsYSksdCE9PXZvaWQgMCYmZi5vcGVuVVJMKHQpfX0scmVmOml9KSkpO2V4cG9ydHtwIGFzIEFuY2hvcn07XG4vLyMgc291cmNlTWFwcGluZ1VSTD1BbmNob3IuanMubWFwXG4iXSwibmFtZXMiOlsianN4IiwiZyIsImlzV2ViIiwibSIsInN0eWxlZCIsImMiLCJTaXphYmxlVGV4dCIsInMiLCJmb3J3YXJkUmVmIiwibCIsIkxpbmtpbmciLCJmIiwicCIsIm8iLCJleHRyYWN0YWJsZSIsImkiLCJuYW1lIiwidGFnIiwiYWNjZXNzaWJpbGl0eVJvbGUiLCJocmVmIiwidCIsInRhcmdldCIsInIiLCJlIiwib25QcmVzcyIsImEiLCJuIiwiY2FsbCIsIm9wZW5VUkwiLCJyZWYiLCJBbmNob3IiXSwic291cmNlUm9vdCI6IiJ9
//# sourceURL=webpack-internal:///../../node_modules/tamagui/dist/esm/views/Anchor.js
```

### Expected Behavior

Builds successfully as with previous versions

### Tamagui Version

```markdown
1.13.4 fails
1.13.3 works
```

### Reproduction

```markdown
Unfortunately can't repo but looking for help :(
```

### System Info

```markdown
** some things have been filtered out

System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 55.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/Code/**filter**/node_modules/.bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.3
  npmPackages:
    @babel/plugin-proposal-class-properties: ^7.18.6 => 7.18.6 
    @manypkg/cli: ^0.20.0 => 0.20.0 
    @react-native-community/netinfo: 9.3.5 => 9.3.5 
    @types/jest: ^29.4.0 => 29.4.0 
    @types/jwt-decode: ^3.1.0 => 3.1.0 
    @types/react: ^18.0.26 => 18.0.28 
    @typescript-eslint/eslint-plugin: ^5.44.0 => 5.54.0 
    @typescript-eslint/parser: ^5.44.0 => 5.54.0 
    cross-env: ^7.0.3 => 7.0.3 
    customize-cra: ^1.0.0 => 1.0.0 
    eslint: ^8.21.0 => 8.35.0 
    eslint-import-resolver-typescript: ^3.5.2 => 3.5.3 
    eslint-plugin-import: ^2.26.0 => 2.27.5 
    eslint-plugin-react: ^7.31.11 => 7.32.2 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    jest: ^29.4.1 => 29.4.3 
    prettier: ^2.5.1 => 2.8.4 
    react: 18.1.0 => 18.1.0 
    react-app-rewired: ^2.2.1 => 2.2.1 
    react-hook-form: ^7.42.1 => 7.43.4 
    react-native-vector-icons: ^9.2.0 => 9.2.0 
    ts-jest: ^29.0.5 => 29.0.5 
    ts-node: ^10.9.1 => 10.9.1 
    turbo: ^1.4.2 => 1.8.3 
    typescript: ^4.9.5 => 4.9.5 
    yarn: ^1.22.19 => 1.22.19
```

**Comment by VladyslavKochetkov** [comment]
This is quite weird. I went straight into `node_modules/tamagui/dist/esm/views/Anchor.js` and I changed it to the following (which is the same thing, I just ran it through prettier and separated the variable definitions and the errors went away.

```js
import {
    jsx as g
} from "react/jsx-runtime";
import {
    isWeb as m,
    styled as c
} from "@tamagui/core";
import {
    SizableText as s
} from "@tamagui/text";
import {
    forwardRef as l
} from "react";
import {
    Linking as f
} from "react-native";
const o = c(s, {
        name: "Anchor",
        tag: "a",
        accessibilityRole: "link"
    });

const p = o.extractable(l(({
    href: t,
    target: r,
    ...e
}, i) => g(o, {
    ...e,
    ...m ? {
        href: t,
        target: r
    } : {
        onPress: a => {
            var n;
            (n = e.onPress) == null || n.call(e, a), t !== void 0 && f.openURL(t)
        }
    },
    ref: i
})));


export {
    p as Anchor
};
```

**Comment by natew** [comment]
I turned on minification for performance but I’m regretting it now since it seems sourcemaps aren’t being picked up in a variety of places.

**Comment by VladyslavKochetkov** [comment]
> I turned on minification for performance but I’m regretting it now since it seems sourcemaps aren’t being picked up in a variety of places. 

Any suggestions on how to mitigate this issue, ideally I'd like to upgrade to 1.14 to not be too behind. @natew

**Comment by natew** [comment]
I've turned off minification, release going out now.

**Comment by VladyslavKochetkov** [comment]
Thank you so much 🙏

**Comment by dohomi** [comment]
@natew I had many issues with core esbuild due to the output files. I think it would be worth considering moving from esbuild => tsup because the defaults there seems more optimised for typescript use and it uses esbuild under the hood

**Comment by VladyslavKochetkov** [comment]
Seems to be resolved after your changes 👍
