### ISSUE TITLE
Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules [NEXT 12]

### ISSUE THREAD

**Issue by sunel-pyt** [tamagui/tamagui#95]
**Describe the bug**
```
Warning: createTamagui called twice (maybe HMR)
Already configured mediaQueries once (you may have called getMedia() before configureMedia())
Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at SafeAreaProvider (/Users/prohertz/Documents/reliance-react/node_modules/tamagui/src/views/SafeAreaProvider.tsx:12:3)
    at conf.Provider (/Users/prohertz/Documents/reliance-react/node_modules/tamagui/src/createTamagui.tsx:14:22)
    at NextThemeProvider (webpack-internal:///./node_modules/@tamagui/next-theme/dist/jsx/NextTheme.js:43:53)
    at Hydrate (/Users/prohertz/Documents/reliance-react/node_modules/react-query/lib/react/Hydrate.js:33:23)
```
**To Reproduce**
Latest version of ui with. next 12

```
Unhandled Runtime Error
SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

Call Stack
updateInserted
node_modules/@tamagui/core/dist/esm/helpers/insertStyleRule.js (43:28)
eval
node_modules/@tamagui/core/dist/esm/helpers/insertStyleRule.js (68:0)
./node_modules/@tamagui/core/dist/esm/helpers/insertStyleRule.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (1974:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/core/dist/esm/Tamagui.js (10:82)
./node_modules/@tamagui/core/dist/esm/Tamagui.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (1611:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/core/dist/esm/index.js (14:66)
./node_modules/@tamagui/core/dist/esm/index.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (2194:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/animate-presence/dist/jsx/AnimatePresence.js (7:71)
./node_modules/@tamagui/animate-presence/dist/jsx/AnimatePresence.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (160:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/animate-presence/dist/jsx/index.js (6:74)
./node_modules/@tamagui/animate-presence/dist/jsx/index.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (204:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/animations-reanimated/dist/jsx/createAnimations.js (5:83)
./node_modules/@tamagui/animations-reanimated/dist/jsx/createAnimations.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (226:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@tamagui/animations-reanimated/dist/jsx/index.js (4:75)
./node_modules/@tamagui/animations-reanimated/dist/jsx/index.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (237:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./node_modules/@atom/core/dist/jsx/index.js (8:88)
./node_modules/@atom/core/dist/jsx/index.js
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (61:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./theme/config.ts (2:68)
./theme/config.ts
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (9180:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (288:21)
eval
webpack-internal:///./pages/_app.tsx (10:71)
./pages/_app.tsx
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/pages/_app.js (9158:1)
options.factory
/_next/static/chunks/webpack.js (633:31)
__webpack_require__
file:///Users/prohertz/Documents/reliance-react/.next/static/chunks/webpack.js (37:33)
```

**Comment by natew** [comment]
Unfortunately need a reproduction for something like this, hard tot ell what's going on.

**Comment by natew** [comment]
Feel free to re-open with repro, don't see it happening on latest.
