### ISSUE TITLE
Cannot find module 'pnpapi'

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#991]
### Current Behavior

Hello,
I have a (big) working project with tamagui which I worked with the last 6 months. I try to regularly keep up to date with tamagui versions, and today I migrated from 1.14.4 to 1.15.21 and I am getting this error when I start the next app (with the classic yarn dev):

```
      Tamagui built config and components:

        Config     ./.tamagui/tamagui.config.cjs
        Components ./.tamagui/tamagui-components.config.cjs
             ./.tamagui/myui-components.config.cjs

Building [
  '/Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/tamagui.config.ts'
]
Tamagui failed loading the pre-built tamagui.config.ts

  Cannot find module 'pnpapi'
Require stack:
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createEvaluator.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/plugin.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/node_modules/@tamagui/next-plugin/dist/cjs/withTamagui.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/node_modules/@tamagui/next-plugin/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/next.config.js
  Error: Cannot find module 'pnpapi'
Require stack:
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createEvaluator.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/plugin.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/node_modules/@tamagui/next-plugin/dist/cjs/withTamagui.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/node_modules/@tamagui/next-plugin/dist/cjs/index.js
- /Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/next.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.mod._resolveFilename (/Users/simone/dev/myproject/myproject-frontend-monorepo/apps/myproject-admin/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at Module.require (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/require.js:56:22)
    at require (node:internal/modules/cjs/helpers:102:18)
    at generateBinPath (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1854:14)
    at esbuildCommandAndArgs (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1907:31)
    at ensureServiceIsRunning (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:2071:25)
    at Object.build (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1962:26)
    at bundle (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/bundle.js:96:33)
    at async Promise.all (index 0)
    at async bundleConfig (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:98:3)
    at async loadTamagui (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:64:24)
    at async Object.load [as loadTamagui] (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:92:42)
    at async extractToClassNames (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/loader.js:62:23)

    You can see if it loads in the node repl:

    require("./pnpapi").default


Tamagui Webpack Loader Error:
   The "path" argument must be of type string. Received type function ([Function (anonymous)] {
...)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)] {
...)
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.join (node:path:1172:7)
    at generateBinPath (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1859:32)
    at esbuildCommandAndArgs (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1907:31)
    at ensureServiceIsRunning (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:2071:25)
    at Object.build (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/esbuild/lib/main.js:1962:26)
    at bundle (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/bundle.js:96:33)
    at async Promise.all (index 0)
    at async bundleConfig (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/bundleConfig.js:98:3)
    at async loadTamagui (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:64:24)
    at async Object.load [as loadTamagui] (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:92:42)
    at async extractToClassNames (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/Users/simone/dev/myproject/myproject-frontend-monorepo/node_modules/tamagui-loader/dist/cjs/loader.js:62:23)

```

### Expected Behavior

By the moment that no breaking changes appears to have been documented in the release notes, the app should start as usual

### Tamagui Version

```markdown
1.15.21
```

### Reproduction

```markdown
I cannot give you reproduction steps, becuase the project at this point is huge.
I can just say that it was working very well and has no particular customizations, I used upgrade:tamagui script without any problem quite frequently, but this time is breaking
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 112.1.50.119
    Chrome: 112.0.5615.137
    Firefox: 109.0.1
    Firefox Developer Edition: 113.0
    Safari: 16.1
```

**Comment by la55u** [comment]
The second error ` The "path" argument must be of type string.` is because esbuild has to be upgraded to the latest I believe.

**Comment by apperside** [comment]
upgraded to 0.17.17, it works, thanks. I dnd't understood that I needed to update it.
Thanks dude, you saved me a lot of time :-)
